CREATE SCALAR FUNCTION deyeStringToArrayStr WITH com.semptian.udf.strhandle.DeyeStringToArrayStr;
CREATE SCALAR FUNCTION deyeProduceAttachmentSuffix WITH com.semptian.udf.fieldproduction.DeyeProduceAttachmentSuffix;
CREATE SCALAR FUNCTION deyeProduceRowKey WITH com.semptian.udf.fieldproduction.DeyeProduceRowKey;
CREATE SCALAR FUNCTION deyeProduceAccessDirection WITH com.semptian.udf.fieldproduction.DeyeProduceAccessDirection;
CREATE SCALAR FUNCTION deyeTryToArrayStr WITH com.semptian.udf.strhandle.DeyeTryToArrayStr;

CREATE TABLE v64_dwd_pr_tool (
	data_type String,
	data_type_map String,
	child_type String,
	child_type_map String,
	`action` String,
	action_map String,
	auth_account String,
	auth_type String,
	auth_type_map String,
	data_source String,
	data_source_map String,
	mobile_phone String,
	uparea_id String,
	uparea_id_map String,
	username String,
	password String,
	user_nick String,
	user_id String,
	imei String,
	imsi String,
	other_imei String,
	relate_imei String,
	base_station_id String,
	isp_id String,
	isp_id_map String,
	internet_land String,
	ownership_land String,
	application_layer_protocol String,
	down_teid String,
	tunnel_type String,
	up_teid String,
	protocol_type String,
	protocol_type_map String,
	strsrc_ip String,
	strsrc_ip_v6 String,
	strdst_ip String,
	strdst_ip_v6 String,
	dst_port Integer,
	dst_port_v6 Integer,
	src_port Integer,
	src_port_v6 Integer,
	src_ip_type Integer,
	src_ip_country String,
	src_ip_province String,
	src_ip_city String,
	src_ip_address String,
	src_ip_longitude Double,
	src_ip_latitude Double,
	dst_ip_type Integer,
	dst_ip_country String,
	dst_ip_province String,
	dst_ip_city String,
	dst_ip_address String,
	dst_ip_longitude Double,
	dst_ip_latitude Double,
	host String,
	hardware_sign String,
	hardware_type String,
	local_action String,
	mac String,
	os_name String,
	os_version String,
	terminal_type String,
	terminal_type_map String,
	browse_version String,
	android_id String,
	terminal_imei String,
	terminal_imsi String,
	terminal_mac String,
	file_id String,
	file_path String,
	file_size Integer,
	attach_num Integer,
	attach_names String,
	attach_sizes String,
	attach_download_path String,
	attach_md5s String,
	attach_text String,
	subject String,
	keywords String,
	`text` String,
	lang_type String,
	content String,
	message String,
	url String,
	`domain` String,
	tool_name String,
	tool_type String,
	data_id String,
	capture_time Long,
	capture_day String,
	capture_hour Integer,
	insert_time Long,
	mark String,
	device_id String,
	trace_id String,
	app_version String,
	app_list String,
	uc_login_flag String,
	cookie String,
	referer String,
	app_pkg_name String,
	head_url String,
	address String,
	from_app String,
	dev_name String,
	dev_no String,
	peer_pwd String,
	peer_user String,
	safe_answer String,
	safe_question String,
	to_client_id String,
	wlw_get_flag String,
	file_name String,
	user_agent String,
	app_soft_name String,
	create_time Long,
	goods_num Long,
	trans_file_size Long,
	transfile_path String,
	webshare_icp String,
	inner_id String,
	link_url String,
	oper_time Long,
	proxy_account String,
	proxy_address String,
	proxy_provider String,
	proxy_type String,
	latitude Double,
	longitude Double,
	abstract String,
	brand String,
	favorite_tags String,
	host_url_tag String,
	icp_provider String,
	remark String,
	session_id String,
	soft_name String,
	content_type String,
	stream_end_time Long,
	dev_id String,
	model String,
	entity_list String,
	province_attribution String,
	time_span String,
	number_risk_level String,
	radius_risk String,
	roam_type String,
	terrorist_area String,
	sensitive_area String,
	format_virtual_account String,
	format_username String,
	norm_data_type String,
	important_target_flag Integer
) WITH (
	'type' = 'kafka',
	'topic' = 'v64_dwd_pr_tool',
	'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
	'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
	'group.id' = 'ads_pr_tool',
	'security.mode.flag' = 'false',
	'enable.auto.commit' = 'false',
	'auto.offset.reset' = 'latest',
	'session.timeout.ms' = '30000',
	'format.type' = 'avro',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
);

CREATE TABLE deye_v64_tool (
	abstractField String,
	actionField String,
	action_mapField String,
	app_listField String,
	attach_namesField LISTOBJ,
	attach_numField Integer,
	attach_sizesField LISTOBJ,
	attach_textField String,
	auth_accountField String,
	auth_typeField String,
	auth_type_mapField String,
	base_station_idField String,
	capture_dayField String,
	capture_timeField Long,
	child_typeField String,
	child_type_mapField String,
	data_sourceField String,
	data_source_mapField String,
	data_typeField String,
	data_type_mapField String,
	norm_data_typeField String,
	data_idField String,
	dev_nameField String,
	domainField String,
	dst_portField Integer,
	favorite_tagsField String,
	file_nameField String,
	file_pathField String,
	file_sizeField Integer,
	icp_providerField String,
	imeiField String,
	imsiField String,
	insert_timeField Long,
	internet_landField String,
	isp_idField String,
	isp_id_mapField String,
	lang_typeField LISTOBJ,
	macField String,
	mobile_phoneField String,
	os_nameField String,
	ownership_landField String,
	passwordField String,
	peer_pwdField String,
	peer_userField String,
	proxy_accountField String,
	proxy_addressField String,
	proxy_providerField String,
	subjectField String,
	src_portField Integer,
	strdst_ipField String,
	strsrc_ipField String,
	src_ip_countryField String,
	dst_ip_countryField String,
	keywordsField String,
	textField String,
	tool_nameField String,
	uparea_idField String,
	uparea_id_mapField String,
	usernameField String,
	wlw_get_flagField String,
	read_userField LISTOBJ,
	_id String,
	_attachment LISTOBJ,
	commonText_all String,
	terminal_typeField String,
	terminal_type_mapField String,
	network_typeField String,
	access_directionField String,
	virtual_accountField LISTOBJ,
	ip_typeField String,
	country_attribution_latitude String,
	province_attribution_latitude String,
	isp_latitude String,
	time_span_latitude String,
	number_risk_level_latitude String,
	radius_risk_latitude String,
	roam_latitude String,
	terrorist_area_latitude String,
	sensitive_area_latitude String,
    uparea_id_latitude String
) WITH (
	'type' = 'elasticsearch',
'max.failure.count' = '3',
	'url' = '172.16.80.162:12000',
	'primaryKey' = '_id',
	'userName' = '',
	'password' = '',
	'security.mode.flag' = 'false',
	'partition.field' = 'capture_dayField',
	'partition.method' = 'month',
        'es.socket.timeout' = '1200000',
	'flush.length' = '2000',
	'flush.size' = '20',
	'request.flag' = '1',
    'backoff.retries' = '3',
	'flush.interval' = '60',
	'tableName' = 'deye_v64_tool',
	'sink.nullable' = 'true'
);

CREATE TABLE deye_v64_tool_detail (
	_data_abstract String,
	_data_action String,
	_data_action_map String,
	_data_app_list String,
	_data_attach_download_path String,
	_data_attach_md5s String,
	_data_attach_names String,
	_data_attach_num String,
	_data_attach_sizes String,
	_data_attach_text String,
	_data_auth_account String,
	_data_auth_type String,
	_data_auth_type_map String,
	_data_base_station_id String,
	_data_capture_day String,
	_data_capture_time String,
	_data_child_type String,
	_data_child_type_map String,
	_data_data_source String,
	_data_data_source_map String,
	_data_data_type String,
	_data_data_type_map String,
	_data_norm_data_type String,
	_data_data_id String,
	_data_dev_name String,
	_data_domain String,
	_data_dst_port String,
	_data_favorite_tags String,
	_data_file_id String,
	_data_file_name String,
	_data_file_path String,
	_data_file_size String,
	_data_icp_provider String,
	_data_imei String,
	_data_imsi String,
	_data_insert_time String,
	_data_internet_land String,
	_data_isp_id String,
	_data_isp_id_map String,
	_data_lang_type String,
	_data_mac String,
	_data_mobile_phone String,
	_data_os_name String,
	_data_ownership_land String,
	_data_password String,
	_data_peer_pwd String,
	_data_peer_user String,
	_data_proxy_account String,
	_data_proxy_address String,
	_data_proxy_provider String,
	_data_proxy_type String,
	_data_subject String,
	_data_src_port String,
	_data_strdst_ip String,
	_data_strsrc_ip String,
	_data_src_ip_country String,
	_data_src_ip_province String,
	_data_src_ip_city String,
	_data_src_ip_address String,
	_data_src_ip_longitude String,
	_data_src_ip_latitude String,
	_data_dst_ip_country String,
	_data_dst_ip_province String,
	_data_dst_ip_city String,
	_data_dst_ip_address String,
	_data_dst_ip_longitude String,
	_data_dst_ip_latitude String,
	_data_keywords String,
	_data_text String,
	_data_tool_name String,
	_data_uparea_id String,
	_data_uparea_id_map String,
	_data_username String,
	_data_wlw_get_flag String,
	_data_read_user String,
	rowKey String,
	_attachment String,
	resourceTableName String,
	resourceType String,
	_data_terminal_type String,
	_data_terminal_type_map String,
	_data_network_type String,
	_data_access_direction String,
	_data_virtual_account String,
	_data_ip_type String,
	_mark_country_attribution_latitude String,
	_mark_province_attribution_latitude String,
	_mark_isp_latitude String,
	_mark_time_span_latitude String,
	_mark_number_risk_level_latitude String,
	_mark_radius_risk_latitude String,
	_mark_roam_latitude String,
	_mark_ownership_src_ip_latitude String,
	_mark_ownership_dst_ip_latitude String,
	_mark_terrorist_area_latitude String,
	_mark_sensitive_area_latitude String,
    _mark_uparea_id_latitude String,
    _feature_capture_time String,
    _feature_source String,
    _feature_destination String,
	_id String
) WITH (
	'type' = 'hbase',
	'hbase-site.xml'='/usr/hdp/current/hbase-client/conf/hbase-site.xml',
	'primaryKey' = '_id',
	'hbase.zookeeper.quorum' = '172.16.80.10:2181',
	'security.mode.flag' = 'false',
	'partition.field' = '_data_capture_day',
	'partition.method' = 'month',
	'tableName' = 'deye_v64_tool_detail',
    'namespace' = 'dw',
    'table.cf.mapping' = 'B:_data_abstract,_data_action,_data_action_map,_data_app_list,_data_attach_download_path,_data_attach_md5s,_data_attach_names,_data_attach_num,_data_attach_sizes,_data_attach_text,_data_auth_account,_data_auth_type,_data_auth_type_map,_data_base_station_id,_data_capture_day,_data_capture_time,_data_child_type,_data_child_type_map,_data_data_source,_data_data_source_map,_data_data_type,_data_data_type_map,_data_norm_data_type,_data_data_id,_data_dev_name,_data_domain,_data_dst_port,_data_favorite_tags,_data_file_id,_data_file_name,_data_file_path,_data_file_size,_data_icp_provider,_data_imei,_data_imsi,_data_insert_time,_data_internet_land,_data_isp_id,_data_isp_id_map,_data_lang_type,_data_mac,_data_mobile_phone,_data_os_name,_data_ownership_land,_data_password,_data_peer_pwd,_data_peer_user,_data_proxy_account,_data_proxy_address,_data_proxy_provider,_data_proxy_type,_data_subject,_data_src_port,_data_strdst_ip,_data_strsrc_ip,_data_src_ip_country,_data_src_ip_province,_data_src_ip_city,_data_src_ip_address,_data_src_ip_longitude,_data_src_ip_latitude,_data_dst_ip_country,_data_dst_ip_province,_data_dst_ip_city,_data_dst_ip_address,_data_dst_ip_longitude,_data_dst_ip_latitude,_data_keywords,_data_text,_data_tool_name,_data_uparea_id,_data_uparea_id_map,_data_username,_data_wlw_get_flag,_data_read_user,rowKey,_attachment,resourceTableName,resourceType,_data_terminal_type,_data_terminal_type_map,_data_network_type,_data_access_direction,_data_virtual_account,_data_ip_type;C:_mark_country_attribution_latitude,_mark_province_attribution_latitude,_mark_isp_latitude,_mark_time_span_latitude,_mark_number_risk_level_latitude,_mark_radius_risk_latitude,_mark_roam_latitude,_mark_ownership_src_ip_latitude,_mark_ownership_dst_ip_latitude,_mark_terrorist_area_latitude,_mark_sensitive_area_latitude,_mark_uparea_id_latitude,_feature_capture_time,_feature_source,_feature_destination'
);

INSERT INTO 
	deye_v64_tool
SELECT
	abstract as abstractField,
	`action` as actionField,
	action_map as action_mapField,
	app_list as app_listField,
	attach_names as attach_namesField,
	attach_num as attach_numField,
	attach_sizes as attach_sizesField,
	attach_text as attach_textField,
	auth_account as auth_accountField,
	auth_type as auth_typeField,
	auth_type_map as auth_type_mapField,
	base_station_id as base_station_idField,
	capture_day as capture_dayField,
	capture_time as capture_timeField,
	child_type as child_typeField,
	child_type_map as child_type_mapField,
	data_source as data_sourceField,
	data_source_map as data_source_mapField,
	data_type as data_typeField,
	data_type_map as data_type_mapField,
	norm_data_type as norm_data_typeField,
	data_id as data_idField,
	dev_name as dev_nameField,
	`domain` as domainField,
	IF(dst_port_v6=0,dst_port,dst_port_v6) as dst_portField,
	favorite_tags as favorite_tagsField,
	file_name as file_nameField,
	file_path as file_pathField,
	file_size as file_sizeField,
	icp_provider as icp_providerField,
	imei as imeiField,
	imsi as imsiField,
	insert_time as insert_timeField,
	internet_land as internet_landField,
	isp_id as isp_idField,
	isp_id_map as isp_id_mapField,
	deyeTryToArrayStr(lang_type) as lang_typeField,
	mac as macField,
	mobile_phone as mobile_phoneField,
	os_name as os_nameField,
	ownership_land as ownership_landField,
	password as passwordField,
	peer_pwd as peer_pwdField,
	peer_user as peer_userField,
	proxy_account as proxy_accountField,
	proxy_address as proxy_addressField,
	proxy_provider as proxy_providerField,
	subject as subjectField,
	IF(src_port_v6=0,src_port,src_port_v6) as src_portField,
	IF(strdst_ip_v6='',strdst_ip,strdst_ip_v6) as strdst_ipField,
	IF(strsrc_ip_v6='',strsrc_ip,strsrc_ip_v6) as strsrc_ipField,
	src_ip_country as src_ip_countryField,
	dst_ip_country as dst_ip_countryField,
	keywords as keywordsField,
	`text` as textField,
	tool_name as tool_nameField,
	uparea_id as uparea_idField,
	uparea_id_map as uparea_id_mapField,
	username as usernameField,
	wlw_get_flag as wlw_get_flagField,
	'' as read_userField,
	deyeProduceRowKey(data_id,'tool',capture_time) as _id,
	deyeProduceAttachmentSuffix(attach_names) as _attachment,
	CONCAT_WS('$#',abstract,attach_names,attach_text,auth_account,base_station_id,dev_name,`domain`,CAST(IF(dst_port_v6=0,dst_port,dst_port_v6) AS VARCHAR),file_name,icp_provider,imei,isp_id,mac,mobile_phone,os_name,peer_user,proxy_account,subject,CAST(IF(src_port_v6=0,src_port,src_port_v6) AS VARCHAR),IF(strdst_ip_v6='',strdst_ip,strdst_ip_v6),IF(strsrc_ip_v6='',strsrc_ip,strsrc_ip_v6),keywords,`text`,tool_name,username,terminal_type_map,password) as commonText_all,
	terminal_type as terminal_typeField,
	terminal_type_map as terminal_type_mapField,
	'' as network_typeField,
	deyeProduceAccessDirection(src_ip_country,dst_ip_country) as access_directionField,
	deyeStringToArrayStr(true,username) as virtual_accountField,
	IF(src_ip_type=0 AND dst_ip_type=0,'0','1') as ip_typeField,
	ownership_land as country_attribution_latitude,
	province_attribution as province_attribution_latitude,
	IF(isp_id='99','',isp_id) as isp_latitude,
	time_span as time_span_latitude,
	number_risk_level as number_risk_level_latitude,
	radius_risk as radius_risk_latitude,
	roam_type as roam_latitude,
	terrorist_area as terrorist_area_latitude,
	sensitive_area as sensitive_area_latitude,
    uparea_id as uparea_id_latitude
FROM 
	v64_dwd_pr_tool;

INSERT INTO 
	deye_v64_tool_detail
SELECT
	abstract as _data_abstract,
	`action` as _data_action,
	action_map as _data_action_map,
	app_list as _data_app_list,
	attach_download_path as _data_attach_download_path,
	attach_md5s as _data_attach_md5s,
	attach_names as _data_attach_names,
	CAST(attach_num AS VARCHAR) as _data_attach_num,
	attach_sizes as _data_attach_sizes,
	attach_text as _data_attach_text,
	auth_account as _data_auth_account,
	auth_type as _data_auth_type,
	auth_type_map as _data_auth_type_map,
	base_station_id as _data_base_station_id,
	capture_day as _data_capture_day,
	CAST(capture_time AS VARCHAR) as _data_capture_time,
	child_type as _data_child_type,
	child_type_map as _data_child_type_map,
	data_source as _data_data_source,
	data_source_map as _data_data_source_map,
	data_type as _data_data_type,
	data_type_map as _data_data_type_map,
	norm_data_type as _data_norm_data_type,
	data_id as _data_data_id,
	dev_name as _data_dev_name,
	`domain` as _data_domain,
	CAST(IF(dst_port_v6=0,dst_port,dst_port_v6) AS VARCHAR) as _data_dst_port,
	favorite_tags as _data_favorite_tags,
	file_id as _data_file_id,
	file_name as _data_file_name,
	file_path as _data_file_path,
	CAST(file_size AS VARCHAR) as _data_file_size,
	icp_provider as _data_icp_provider,
	imei as _data_imei,
	imsi as _data_imsi,
	CAST(insert_time AS VARCHAR) as _data_insert_time,
	internet_land as _data_internet_land,
	isp_id as _data_isp_id,
	isp_id_map as _data_isp_id_map,
	deyeTryToArrayStr(lang_type) as _data_lang_type,
	mac as _data_mac,
	mobile_phone as _data_mobile_phone,
	os_name as _data_os_name,
	ownership_land as _data_ownership_land,
	password as _data_password,
	peer_pwd as _data_peer_pwd,
	peer_user as _data_peer_user,
	proxy_account as _data_proxy_account,
	proxy_address as _data_proxy_address,
	proxy_provider as _data_proxy_provider,
	proxy_type as _data_proxy_type,
	subject as _data_subject,
	CAST(IF(src_port_v6=0,src_port,src_port_v6) AS VARCHAR) as _data_src_port,
	IF(strdst_ip_v6='',strdst_ip,strdst_ip_v6) as _data_strdst_ip,
	IF(strsrc_ip_v6='',strsrc_ip,strsrc_ip_v6) as _data_strsrc_ip,
	src_ip_country as _data_src_ip_country,
	src_ip_province as _data_src_ip_province,
	src_ip_city as _data_src_ip_city,
	src_ip_address as _data_src_ip_address,
	CAST(src_ip_longitude AS VARCHAR) as _data_src_ip_longitude,
	CAST(src_ip_latitude AS VARCHAR) as _data_src_ip_latitude,
	dst_ip_country as _data_dst_ip_country,
	dst_ip_province as _data_dst_ip_province,
	dst_ip_city as _data_dst_ip_city,
	dst_ip_address as _data_dst_ip_address,
	CAST(dst_ip_longitude AS VARCHAR) as _data_dst_ip_longitude,
	CAST(dst_ip_latitude AS VARCHAR) as _data_dst_ip_latitude,
	keywords as _data_keywords,
	`text` as _data_text,
	tool_name as _data_tool_name,
	uparea_id as _data_uparea_id,
	uparea_id_map as _data_uparea_id_map,
	username as _data_username,
	wlw_get_flag as _data_wlw_get_flag,
	'' as _data_read_user,
	deyeProduceRowKey(data_id,'tool',capture_time) as rowKey,
	deyeProduceAttachmentSuffix(attach_names) as _attachment,
	'deye_v64_tool' as resourceTableName,
	'3' as resourceType,
	terminal_type as _data_terminal_type,
	terminal_type_map as _data_terminal_type_map,
	'' as _data_network_type,
	deyeProduceAccessDirection(src_ip_country,dst_ip_country) as _data_access_direction,
	deyeStringToArrayStr(true,username) as _data_virtual_account,
	IF(src_ip_type=0 AND dst_ip_type=0,'0','1') as _data_ip_type,
	ownership_land as _mark_country_attribution_latitude,
	province_attribution as _mark_province_attribution_latitude,
	IF(isp_id='99','',isp_id) as _mark_isp_latitude,
	time_span as _mark_time_span_latitude,
	number_risk_level as _mark_number_risk_level_latitude,
	radius_risk as _mark_radius_risk_latitude,
	roam_type as _mark_roam_latitude,
	src_ip_country  as _mark_ownership_src_ip_latitude,
	dst_ip_country as _mark_ownership_dst_ip_latitude,
	terrorist_area as _mark_terrorist_area_latitude,
	sensitive_area as _mark_sensitive_area_latitude,
    uparea_id as _mark_uparea_id_latitude,
    CONCAT('["', LEFT(capture_day,7), '","', capture_day, '"]') as _feature_capture_time,
    CONCAT('["', IF(strsrc_ip_v6='',strsrc_ip,strsrc_ip_v6), '","', auth_account, '","', src_ip_city, '"]') as _feature_source,
    CONCAT('["', IF(strdst_ip_v6='',strdst_ip,strdst_ip_v6), '","', dst_ip_city, '"]') as _feature_destination,
	deyeProduceRowKey(data_id,'tool',capture_time) as _id
FROM 
	v64_dwd_pr_tool;

