CREATE SCALAR FUNCTION deyeProduceIpType WITH com.semptian.udf.fieldproduction.DeyeProduceIpType;
CREATE SCALAR FUNCTION deyeVerifyIp WITH com.semptian.udf.verify.DeyeVerifyIp;
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;
CREATE SCALAR FUNCTION deyeUserNameNorm WITH com.semptian.udf.normalization.DeyeUserNameNorm;
CREATE SCALAR FUNCTION deyeMacNorm WITH com.semptian.udf.normalization.DeyeMacNorm;
CREATE SCALAR FUNCTION deyeProduceRelativeUrl WITH com.semptian.udf.fieldproduction.DeyeProduceRelativeUrl;
CREATE SCALAR FUNCTION deyeSubDomainNorm WITH com.semptian.udf.normalization.DeyeSubDomainNorm;
CREATE SCALAR FUNCTION deyePasswordNorm WITH com.semptian.udf.normalization.DeyePasswordNorm;
CREATE SCALAR FUNCTION deyeIpNorm WITH com.semptian.udf.normalization.DeyeIpNorm;
CREATE SCALAR FUNCTION deyeSuperDomainNorm WITH com.semptian.udf.normalization.DeyeSuperDomainNorm;
CREATE SCALAR FUNCTION deyeVerifyTimestamp WITH com.semptian.udf.timestamphandle.DeyeVerifyTimestamp;
CREATE SCALAR FUNCTION deyeCompleteActionTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteActionTypeMap;
CREATE SCALAR FUNCTION deyeCompleteUpareaTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteUpareaTypeMap;
CREATE SCALAR FUNCTION deyeCompleteIspTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteIspTypeMap;
CREATE SCALAR FUNCTION deyeMobilePhoneNorm WITH com.semptian.udf.normalization.DeyeMobilePhoneNorm;
CREATE SCALAR FUNCTION deyeMoneyNorm WITH com.semptian.udf.normalization.DeyeMoneyNorm;
CREATE SCALAR FUNCTION deyeCompleteAuthTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteAuthTypeMap;
CREATE SCALAR FUNCTION deyeCompleteDataTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteDataTypeMap;
CREATE SCALAR FUNCTION deyeCompleteChildTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteChildTypeMap;
CREATE SCALAR FUNCTION deyeCompleteDataSourceMap WITH com.semptian.udf.dimcomplete.DeyeCompleteDataSourceMap;
CREATE SCALAR FUNCTION deyeCompleteProtocolTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteProtocolTypeMap;
CREATE SCALAR FUNCTION deyeGetRoamType WITH com.semptian.udf.mark.DeyeGetRoamType;
CREATE SCALAR FUNCTION deyeGetSensitiveArea WITH com.semptian.udf.mark.DeyeGetSensitiveArea;
CREATE SCALAR FUNCTION deyeGetTerroristArea WITH com.semptian.udf.mark.DeyeGetTerroristArea;
CREATE SCALAR FUNCTION deyeGetTimeSpan WITH com.semptian.udf.mark.DeyeGetTimeSpan;
CREATE TABLE FUNCTION deyeIpAttributionComp WITH com.semptian.udtf.dimcomplete.DeyeIpAttributionComp;
CREATE TABLE FUNCTION deyeIpAttributionCompV2 WITH com.semptian.udtf.dimcomplete.DeyeIpAttributionCompV2;
CREATE TABLE FUNCTION deyeAuthAccountHandle WITH com.semptian.udtf.normalization.DeyeAuthAccountHandle;
CREATE TABLE FUNCTION deyeDomainHandle WITH com.semptian.udtf.normalization.DeyeDomainHandle;
CREATE TABLE FUNCTION deyeTimeHandle WITH com.semptian.udtf.normalization.DeyeTimeHandle;
CREATE SCALAR FUNCTION deyeGetIspByPhoneNumber WITH com.semptian.udf.mark.DeyeGetIspByPhoneNumber;
CREATE SCALAR FUNCTION deyeGetCountryCodeByPhoneNumber WITH com.semptian.udf.DeyeGetCountryCodeByPhoneNumber;
CREATE SCALAR FUNCTION deyeUrlDecode WITH com.semptian.udf.fieldspecialhandle.DeyeUrlDecode;
CREATE SCALAR FUNCTION deyeVirtualAccountNorm WITH com.semptian.udf.normalization.DeyeVirtualAccountNorm;
CREATE SCALAR FUNCTION deyeProduceImportantTargetFlag WITH com.semptian.udf.fieldproduction.DeyeProduceImportantTargetFlag;
CREATE SCALAR FUNCTION deyeOsNameNorm WITH com.semptian.udf.normalization.DeyeOsNameNorm;

CREATE TABLE ods_pr_source_0031_payment (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_type String,
  proxy_address String,
  proxy_provider String,
  proxy_account String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  src_ip_area String,
  dst_ip_area String,
  service_provider String,
  pay_account String,
  to_id String,
  order_id String,
  goods_name String,
  goods_num Bigint,
  money String,
  order_time Bigint,
  pickup_mobile String,
  pickup_certificate_type String,
  pickup_certificate_code String,
  reg_account_type String,
  reg_account String,
  user_id String,
  content String,
  pickup_name String,
  transaction_amount Double,
  trading_account String,
  sms_code String,
  longitude Double,
  latitude Double,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_text String,
  keywords String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_num Integer,
  attach_download_path String,
  file_size Integer,
  file_path String,
  file_id String,
  tool_type String,
  tool_name String,
  isp_id String,
  device_id String,
  trace_id String,
  session_id String,
  icp_provider String,
  rule_version String,
  record_id String,
  soft_name String,
  favorite_tags String,
  host_url_tag String,
  app_version String,
  remark String,
  model String,
  stream_end_time Bigint,
  up_teid String,
  down_teid String,
  application_layer_protocol String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  mobile_phone String,
  username String,
  password String,
  url String,
  local_action String,
  mac String,
  hardware_type String,
  hardware_sign String,
  os_name String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_0031_payment',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_finance',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE ods_pr_source_0033_netbank (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_type String,
  proxy_address String,
  proxy_provider String,
  proxy_account String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  src_ip_area String,
  dst_ip_area String,
  host String,
  content String,
  trading_account String,
  to_account String,
  lead_word String,
  user_id String,
  money String,
  pay_name String,
  trade_type String,
  from_id String,
  to_id String,
  bind_phone String,
  push String,
  oper_time Bigint,
  user_nick String,
  fun_name String,
  longitude Double,
  latitude Double,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_text String,
  keywords String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_num Integer,
  attach_download_path String,
  file_size Integer,
  file_path String,
  file_id String,
  tool_type String,
  tool_name String,
  isp_id String,
  device_id String,
  trace_id String,
  session_id String,
  icp_provider String,
  rule_version String,
  record_id String,
  soft_name String,
  favorite_tags String,
  host_url_tag String,
  app_version String,
  model String,
  brand String,
  remark String,
  message_id String,
  stream_end_time Bigint,
  up_teid String,
  down_teid String,
  application_layer_protocol String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  username String,
  password String,
  local_action String,
  mac String,
  hardware_type String,
  hardware_sign String,
  os_name String,
  os_version String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_0033_netbank',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_finance',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE ods_pr_source_my0035_digcurrency (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_type String,
  proxy_address String,
  proxy_provider String,
  proxy_account String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  src_ip_area String,
  dst_ip_area String,
  wallet_id String,
  wallet_pwd String,
  user_id String,
  user_nick String,
  from_id String,
  group_num String,
  content String,
  app_pkg_name String,
  sms_code String,
  invite_doce String,
  password_hash_string String,
  longitude Double,
  latitude Double,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_text String,
  keywords String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_num Integer,
  attach_download_path String,
  file_path String,
  file_size Integer,
  file_id String,
  tool_type String,
  tool_name String,
  isp_id String,
  device_id String,
  trace_id String,
  stream_end_time Bigint,
  up_teid String,
  down_teid String,
  application_layer_protocol String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  mobile_phone String,
  username String,
  password String,
  local_action String,
  mac String,
  hardware_type String,
  hardware_sign String,
  os_name String,
  os_version String,
  session_id String,
  icp_provider String,
  rule_version String,
  record_id String,
  soft_name String,
  favorite_tags String,
  host_url_tag String,
  from_nickname String,
  app_version String,
  brand String,
  model String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_my0035_digcurrency',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_finance',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE ods_pr_source_my0049_financial (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_provider String,
  proxy_type String,
  proxy_address String,
  proxy_account String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  dst_ip_area String,
  src_ip_area String,
  host String,
  user_id String,
  pickup_name String,
  user_phone String,
  postal_time Bigint,
  content String,
  pickup_certificate_code String,
  sms_code String,
  address String,
  terminal_imei String,
  terminal_mac String,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  latitude Double,
  longitude Double,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_text String,
  keywords String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_num Integer,
  attach_download_path String,
  file_size Integer,
  file_path String,
  file_id String,
  tool_type String,
  tool_name String,
  isp_id String,
  trace_id String,
  device_id String,
  record_id String,
  favorite_tags String,
  icp_provider String,
  rule_version String,
  soft_name String,
  session_id String,
  host_url_tag String,
  app_version String,
  brand String,
  model String,
  remark String,
  stream_end_time Bigint,
  application_layer_protocol String,
  down_teid String,
  up_teid String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  username String,
  password String,
  url String,
  hardware_sign String,
  mac String,
  hardware_type String,
  os_version String,
  local_action String,
  os_name String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_my0049_financial',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_finance',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE dwd_pr_finance (
  data_type String,
  data_type_map String,
  child_type String,
  child_type_map String,
  `action` String,
  action_map String,
  auth_account String,
  auth_type String,
  auth_type_map String,
  main_account String,
  data_source String,
  data_source_map String,
  mobile_phone String,
  uparea_id String,
  uparea_id_map String,
  username String,
  password String,
  password_hash_string String,
  user_nick String,
  user_id String,
  imei String,
  imsi String,
  base_station_id String,
  isp_id String,
  isp_id_map String,
  internet_land String,
  ownership_land String,
  application_layer_protocol String,
  down_teid String,
  tunnel_type String,
  up_teid String,
  protocol_type String,
  protocol_type_map String,
  strsrc_ip String,
  strsrc_ip_v6 String,
  strdst_ip String,
  strdst_ip_v6 String,
  dst_port Integer,
  dst_port_v6 Integer,
  src_port Integer,
  src_port_v6 Integer,
  src_ip_type Integer,
  src_ip_country String,
  src_ip_province String,
  src_ip_city String,
  src_ip_address String,
  src_ip_longitude Double,
  src_ip_latitude Double,
  dst_ip_type Integer,
  dst_ip_country String,
  dst_ip_province String,
  dst_ip_city String,
  dst_ip_address String,
  dst_ip_longitude Double,
  dst_ip_latitude Double,
  host String,
  hardware_sign String,
  hardware_type String,
  local_action String,
  mac String,
  os_name String,
  os_version String,
  terminal_type String,
  terminal_type_map String,
  terminal_imei String,
  terminal_mac String,
  file_id String,
  file_path String,
  file_size Integer,
  attach_num Integer,
  attach_names String,
  attach_sizes String,
  attach_download_path String,
  attach_md5s String,
  attach_text String,
  subject String,
  keywords String,
  text String,
  lang_type String,
  content String,
  url String,
  `domain` String,
  relative_url String,
  sub_domain String,
  super_domain String,
  tool_name String,
  tool_type String,
  from_id String,
  to_id String,
  from_nickname String,
  from_account String,
  from_account_remark String,
  to_account String,
  to_account_remark String,
  data_id String,
  capture_time Bigint,
  capture_day String,
  capture_hour Integer,
  insert_time Bigint,
  mark String,
  device_id String,
  trace_id String,
  app_version String,
  order_id String,
  order_time Bigint,
  invite_doce String,
  wallet_pwd String,
  user_phone String,
  bind_phone String,
  app_pkg_name String,
  group_num String,
  money Double,
  sms_code String,
  trading_account String,
  wallet_id String,
  address String,
  pickup_certificate_type String,
  pickup_mobile String,
  pickup_name String,
  fun_name String,
  lead_word String,
  pay_name String,
  push String,
  trade_type String,
  transaction_amount Double,
  goods_name String,
  pay_account String,
  reg_account String,
  reg_account_type String,
  service_provider String,
  postal_time Bigint,
  goods_num Bigint,
  oper_time Bigint,
  proxy_account String,
  proxy_address String,
  proxy_provider String,
  proxy_type String,
  latitude Double,
  longitude Double,
  abstract String,
  brand String,
  favorite_tags String,
  host_url_tag String,
  icp_provider String,
  message_id String,
  remark String,
  session_id String,
  soft_name String,
  stream_end_time Bigint,
  model String,
  pickup_certificate_code String,
  entity_list String,
  province_attribution String,
  time_span String,
  number_risk_level String,
  radius_risk String,
  roam_type String,
  terrorist_area String,
  sensitive_area String,
  format_virtual_account String,
  format_username String,
  norm_data_type String,
  important_target_flag Integer
) WITH (
  'type' = 'kafka',
  'topic' = 'v64_dwd_pr_finance',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'security.mode.flag' = 'false',
  'format.type' = 'avro',
  'batch.size'='1048576',
  'acks'='1',
  'linger.ms'='100',
  'buffer.memory'='33554432',
  'retries'='1',
  'feature.max.request.size' = '52428800'
);

CREATE TABLE dwd_pr_tmp (
  data_type String,
  data_type_map String,
  auth_account String,
  mobile_phone String,
  username String,
  password String,
  data_id String,
  capture_time Bigint,
  capture_day String,
  capture_hour Integer,
  insert_time Bigint
) WITH (
  'type' = 'kafka',
  'topic' = 'v64_dwd_pr_tmp',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'security.mode.flag' = 'false',
  'format.type' = 'json',
  'batch.size'='1048576',
  'acks'='1',
  'linger.ms'='100',
  'buffer.memory'='33554432',
  'retries'='1',
  'feature.max.request.size' = '52428800'
  );

INSERT INTO
    dwd_pr_tmp
SELECT
    t1.data_type as data_type,
    deyeCompleteDataTypeMap(t1.data_type, true)[2] as data_type_map,
    t1.auth_account as auth_account,
    t1.mobile_phone as mobile_phone,
    t1.username as username,
    t1.password as password,
    t1.data_id as data_id,
    t1.capture_time as capture_time,
    t1.capture_day as capture_day,
    t1.capture_hour as capture_hour,
    t1.insert_time as insert_time
FROM
    (
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, mobile_phone) as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            '' as password_hash_string,
            '' as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
                WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
                ELSE ''
                END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
                WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
                ELSE ''
                END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            '' as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            '' as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            '' as terminal_imei,
            '' as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            url as url,
            T8.domain_l as `domain`,
            deyeProduceRelativeUrl(url) as relative_url,
            deyeSubDomainNorm(T8.domain_l) as sub_domain,
            deyeSuperDomainNorm(T8.domain_l) as super_domain,
            tool_name as tool_name,
            tool_type as tool_type,
            '' as from_id,
            to_id as to_id,
            '' as from_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            app_version as app_version,
            order_id as order_id,
            order_time as order_time,
            '' as invite_doce,
            '' as wallet_pwd,
            '' as user_phone,
            '' as bind_phone,
            '' as app_pkg_name,
            '' as group_num,
            deyeMoneyNorm(money) as money,
            sms_code as sms_code,
            trading_account as trading_account,
            '' as wallet_id,
            '' as address,
            pickup_certificate_type as pickup_certificate_type,
            pickup_mobile as pickup_mobile,
            pickup_name as pickup_name,
            '' as fun_name,
            '' as lead_word,
            '' as pay_name,
            '' as push,
            '' as trade_type,
            transaction_amount as transaction_amount,
            goods_name as goods_name,
            pay_account as pay_account,
            reg_account as reg_account,
            reg_account_type as reg_account_type,
            service_provider as service_provider,
            0 as postal_time,
            goods_num as goods_num,
            0 as oper_time,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            '' as brand,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            '' as message_id,
            remark as remark,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            pickup_certificate_code as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_0031_payment,
            LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeDomainHandle('', url)) as T8(domain_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '129')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
        UNION ALL
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            '' as password_hash_string,
            user_nick as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            host as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            os_version as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            '' as terminal_imei,
            '' as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            '' as url,
            '' as `domain`,
            '' as relative_url,
            '' as sub_domain,
            '' as super_domain,
            tool_name as tool_name,
            tool_type as tool_type,
            from_id as from_id,
            to_id as to_id,
            '' as from_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            app_version as app_version,
            '' as order_id,
            0 as order_time,
            '' as invite_doce,
            '' as wallet_pwd,
            '' as user_phone,
            bind_phone as bind_phone,
            '' as app_pkg_name,
            '' as group_num,
            deyeMoneyNorm(money) as money,
            '' as sms_code,
            trading_account as trading_account,
            '' as wallet_id,
            '' as address,
            '' as pickup_certificate_type,
            '' as pickup_mobile,
            '' as pickup_name,
            fun_name as fun_name,
            lead_word as lead_word,
            pay_name as pay_name,
            push as push,
            trade_type as trade_type,
            0 as transaction_amount,
            '' as goods_name,
            '' as pay_account,
            '' as reg_account,
            '' as reg_account_type,
            '' as service_provider,
            0 as postal_time,
            0 as goods_num,
            oper_time as oper_time,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            brand as brand,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            message_id as message_id,
            remark as remark,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            '' as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_0033_netbank,
            LATERAL TABLE(
            deyeAuthAccountHandle(
            auth_type,
            auth_account,
            data_type,
            deyeIpNorm(strsrc_ip),
            deyeIpNorm(strsrc_ip_v6),
            deyeIpNorm(strdst_ip),
            deyeIpNorm(strdst_ip_v6),
            capture_time
            )
            ) as T3(auth_type_l, auth_account_l),
            LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '131')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
        UNION ALL
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, mobile_phone) as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            password_hash_string as password_hash_string,
            user_nick as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            '' as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            os_version as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            '' as terminal_imei,
            '' as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            '' as url,
            '' as `domain`,
            '' as relative_url,
            '' as sub_domain,
            '' as super_domain,
            tool_name as tool_name,
            tool_type as tool_type,
            from_id as from_id,
            '' as to_id,
            from_nickname as from_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            app_version as app_version,
            '' as order_id,
            0 as order_time,
            invite_doce as invite_doce,
            wallet_pwd as wallet_pwd,
            '' as user_phone,
            '' as bind_phone,
            app_pkg_name as app_pkg_name,
            group_num as group_num,
            0 as money,
            sms_code as sms_code,
            '' as trading_account,
            wallet_id as wallet_id,
            '' as address,
            '' as pickup_certificate_type,
            '' as pickup_mobile,
            '' as pickup_name,
            '' as fun_name,
            '' as lead_word,
            '' as pay_name,
            '' as push,
            '' as trade_type,
            0 as transaction_amount,
            '' as goods_name,
            '' as pay_account,
            '' as reg_account,
            '' as reg_account_type,
            '' as service_provider,
            0 as postal_time,
            0 as goods_num,
            0 as oper_time,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            brand as brand,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            '' as message_id,
            '' as remark,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            '' as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_my0035_digcurrency,
            LATERAL TABLE(
            deyeAuthAccountHandle(
            auth_type,
            auth_account,
            data_type,
            deyeIpNorm(strsrc_ip),
            deyeIpNorm(strsrc_ip_v6),
            deyeIpNorm(strdst_ip),
            deyeIpNorm(strdst_ip_v6),
            capture_time
            )
            ) as T3(auth_type_l, auth_account_l),
            LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '974')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
        UNION ALL
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            '' as password_hash_string,
            '' as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            host as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            os_version as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            terminal_imei as terminal_imei,
            terminal_mac as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            url as url,
            T8.domain_l as `domain`,
            deyeProduceRelativeUrl(url) as relative_url,
            deyeSubDomainNorm(T8.domain_l) as sub_domain,
            deyeSuperDomainNorm(T8.domain_l) as super_domain,
            tool_name as tool_name,
            tool_type as tool_type,
            '' as from_id,
            '' as to_id,
            '' as from_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            app_version as app_version,
            '' as order_id,
            0 as order_time,
            '' as invite_doce,
            '' as wallet_pwd,
            user_phone as user_phone,
            '' as bind_phone,
            '' as app_pkg_name,
            '' as group_num,
            0 as money,
            sms_code as sms_code,
            '' as trading_account,
            '' as wallet_id,
            address as address,
            '' as pickup_certificate_type,
            '' as pickup_mobile,
            pickup_name as pickup_name,
            '' as fun_name,
            '' as lead_word,
            '' as pay_name,
            '' as push,
            '' as trade_type,
            0 as transaction_amount,
            '' as goods_name,
            '' as pay_account,
            '' as reg_account,
            '' as reg_account_type,
            '' as service_provider,
            postal_time as postal_time,
            0 as goods_num,
            0 as oper_time,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            brand as brand,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            '' as message_id,
            remark as remark,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            pickup_certificate_code as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_my0049_financial,
            LATERAL TABLE(
            deyeAuthAccountHandle(
            auth_type,
            auth_account,
            data_type,
            deyeIpNorm(strsrc_ip),
            deyeIpNorm(strsrc_ip_v6),
            deyeIpNorm(strdst_ip),
            deyeIpNorm(strdst_ip_v6),
            capture_time
            )
            ) as T3(auth_type_l, auth_account_l),
            LATERAL TABLE(deyeDomainHandle('', url)) as T8(domain_l),
            LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '963')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
    ) t1
WHERE (
    CHAR_LENGTH(t1.auth_account) > 128
   OR CHAR_LENGTH(t1.mobile_phone) > 30
   OR CHAR_LENGTH(t1.username) > 512
   OR CHAR_LENGTH(t1.password) > 512
    );

INSERT INTO
  dwd_pr_finance
SELECT
  t1.data_type as data_type,
  deyeCompleteDataTypeMap(t1.data_type, true)[2] as data_type_map,
  t1.child_type as child_type,
  t1.child_type_map as child_type_map,
  t1. `action` as `action`,
  t1.action_map as action_map,
  t1.auth_account as auth_account,
  t1.auth_type as auth_type,
  t1.auth_type_map as auth_type_map,
  t1.main_account as main_account,
  t1.data_source as data_source,
  t1.data_source_map as data_source_map,
  t1.mobile_phone as mobile_phone,
  t1.uparea_id as uparea_id,
  t1.uparea_id_map as uparea_id_map,
  t1.username as username,
  t1.password as password,
  t1.password_hash_string as password_hash_string,
  t1.user_nick as user_nick,
  t1.user_id as user_id,
  t1.imei as imei,
  t1.imsi as imsi,
  t1.base_station_id as base_station_id,
  t1.isp_id as isp_id,
  t1.isp_id_map as isp_id_map,
  t1.internet_land as internet_land,
  t1.ownership_land as ownership_land,
  t1.application_layer_protocol as application_layer_protocol,
  t1.down_teid as down_teid,
  t1.tunnel_type as tunnel_type,
  t1.up_teid as up_teid,
  t1.protocol_type as protocol_type,
  t1.protocol_type_map as protocol_type_map,
  t1.strsrc_ip as strsrc_ip,
  t1.strsrc_ip_v6 as strsrc_ip_v6,
  t1.strdst_ip as strdst_ip,
  t1.strdst_ip_v6 as strdst_ip_v6,
  t1.dst_port as dst_port,
  t1.dst_port_v6 as dst_port_v6,
  t1.src_port as src_port,
  t1.src_port_v6 as src_port_v6,
  t1.src_ip_type as src_ip_type,
  T1.src_ip_country_l as src_ip_country,
  T1.src_ip_province_l as src_ip_province,
  T1.src_ip_city_l as src_ip_city,
  T1.src_ip_address_l as src_ip_address,
  T1.src_ip_longitude_l as src_ip_longitude,
  T1.src_ip_latitude_l as src_ip_latitude,
  t1.dst_ip_type as dst_ip_type,
  T2.dst_ip_country_l as dst_ip_country,
  T2.dst_ip_province_l as dst_ip_province,
  T2.dst_ip_city_l as dst_ip_city,
  T2.dst_ip_address_l as dst_ip_address,
  T2.dst_ip_longitude_l as dst_ip_longitude,
  T2.dst_ip_latitude_l as dst_ip_latitude,
  case
    when position(':' in t1.host)>0 then substring(t1.host,1,position(':' in t1.host) -1)
    else t1.host
  end as host,
  t1.hardware_sign as hardware_sign,
  t1.hardware_type as hardware_type,
  t1.local_action as local_action,
  t1.mac as mac,
  deyeOsNameNorm(t1.os_name) as os_name,
  t1.os_version as os_version,
  t1.terminal_type as terminal_type,
  t1.terminal_type_map as terminal_type_map,
  t1.terminal_imei as terminal_imei,
  t1.terminal_mac as terminal_mac,
  t1.file_id as file_id,
  t1.file_path as file_path,
  t1.file_size as file_size,
  t1.attach_num as attach_num,
  t1.attach_names as attach_names,
  t1.attach_sizes as attach_sizes,
  t1.attach_download_path as attach_download_path,
  t1.attach_md5s as attach_md5s,
  t1.attach_text as attach_text,
  t1.subject as subject,
  t1.keywords as keywords,
  t1.text as text,
  SPLIT_INDEX(IF(LEFT(t1.lang_type,1)='[' AND RIGHT(t1.lang_type,1)=']', SUBSTR(t1.lang_type,2,CHAR_LENGTH(t1.lang_type)-2), t1.lang_type),' ',0) as lang_type,
  t1.content as content,
  deyeUrlDecode(t1.url) as url,
  t1.`domain` as `domain`,
  deyeUrlDecode(t1.relative_url) as relative_url,
  t1.sub_domain as sub_domain,
  t1.super_domain as super_domain,
  t1.child_type_map as tool_name,
  t1.child_type as tool_type,
  t1.from_id as from_id,
  t1.to_id as to_id,
  t1.from_nickname as from_nickname,
  t1.from_account as from_account,
  t1.from_account_remark as from_account_remark,
  t1.to_account as to_account,
  t1.to_account_remark as to_account_remark,
  t1.data_id as data_id,
  t1.capture_time as capture_time,
  t1.capture_day as capture_day,
  t1.capture_hour as capture_hour,
  t1.insert_time as insert_time,
  t1.mark as mark,
  t1.device_id as device_id,
  t1.trace_id as trace_id,
  t1.app_version as app_version,
  t1.order_id as order_id,
  t1.order_time as order_time,
  t1.invite_doce as invite_doce,
  t1.wallet_pwd as wallet_pwd,
  t1.user_phone as user_phone,
  t1.bind_phone as bind_phone,
  t1.app_pkg_name as app_pkg_name,
  t1.group_num as group_num,
  t1.money as money,
  t1.sms_code as sms_code,
  t1.trading_account as trading_account,
  t1.wallet_id as wallet_id,
  t1.address as address,
  t1.pickup_certificate_type as pickup_certificate_type,
  t1.pickup_mobile as pickup_mobile,
  t1.pickup_name as pickup_name,
  t1.fun_name as fun_name,
  t1.lead_word as lead_word,
  t1.pay_name as pay_name,
  t1.push as push,
  t1.trade_type as trade_type,
  t1.transaction_amount as transaction_amount,
  t1.goods_name as goods_name,
  t1.pay_account as pay_account,
  t1.reg_account as reg_account,
  t1.reg_account_type as reg_account_type,
  t1.service_provider as service_provider,
  t1.postal_time as postal_time,
  t1.goods_num as goods_num,
  t1.oper_time as oper_time,
  t1.proxy_account as proxy_account,
  t1.proxy_address as proxy_address,
  t1.proxy_provider as proxy_provider,
  t1.proxy_type as proxy_type,
  t1.latitude as latitude,
  t1.longitude as longitude,
  t1.abstract as abstract,
  t1.brand as brand,
  t1.favorite_tags as favorite_tags,
  t1.host_url_tag as host_url_tag,
  t1.icp_provider as icp_provider,
  t1.message_id as message_id,
  t1.remark as remark,
  t1.session_id as session_id,
  t1.soft_name as soft_name,
  t1.stream_end_time as stream_end_time,
  t1.model as model,
  t1.pickup_certificate_code as pickup_certificate_code,
  t1.entity_list as entity_list,
  t1.province_attribution as province_attribution,
  t1.time_span as time_span,
  t1.number_risk_level as number_risk_level,
  t1.radius_risk as radius_risk,
  t1.roam_type as roam_type,
  deyeGetTerroristArea(
    deyeGetCountryCodeByPhoneNumber(t1.auth_account),
    'DZ',
    T1.src_ip_country_code_l
  ) as terrorist_area,
  deyeGetSensitiveArea(
    deyeGetCountryCodeByPhoneNumber(t1.auth_account),
    'DZ',
    T1.src_ip_country_code_l
  ) as sensitive_area,
  '' AS format_virtual_account,
  LOWER(t1.username) as format_username,
  deyeCompleteDataTypeMap(t1.data_type, true)[1] as norm_data_type,
  deyeProduceImportantTargetFlag(data_type,t1.auth_account,t1.auth_type,deyeIpNorm(strsrc_ip),deyeIpNorm(strsrc_ip_v6),deyeIpNorm(strdst_ip),deyeIpNorm(strdst_ip_v6)) as important_target_flag
FROM
  (
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, mobile_phone) as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      '' as password_hash_string,
      '' as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      '' as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      '' as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      '' as terminal_imei,
      '' as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      url as url,
      T8.domain_l as `domain`,
      deyeProduceRelativeUrl(url) as relative_url,
      deyeSubDomainNorm(T8.domain_l) as sub_domain,
      deyeSuperDomainNorm(T8.domain_l) as super_domain,
      tool_name as tool_name,
      tool_type as tool_type,
      '' as from_id,
      to_id as to_id,
      '' as from_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      app_version as app_version,
      order_id as order_id,
      order_time as order_time,
      '' as invite_doce,
      '' as wallet_pwd,
      '' as user_phone,
      '' as bind_phone,
      '' as app_pkg_name,
      '' as group_num,
      deyeMoneyNorm(money) as money,
      sms_code as sms_code,
      trading_account as trading_account,
      '' as wallet_id,
      '' as address,
      pickup_certificate_type as pickup_certificate_type,
      pickup_mobile as pickup_mobile,
      pickup_name as pickup_name,
      '' as fun_name,
      '' as lead_word,
      '' as pay_name,
      '' as push,
      '' as trade_type,
      transaction_amount as transaction_amount,
      goods_name as goods_name,
      pay_account as pay_account,
      reg_account as reg_account,
      reg_account_type as reg_account_type,
      service_provider as service_provider,
      0 as postal_time,
      goods_num as goods_num,
      0 as oper_time,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      '' as brand,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      '' as message_id,
      remark as remark,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      pickup_certificate_code as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_0031_payment,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeDomainHandle('', url)) as T8(domain_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '129')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
    UNION ALL
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      '' as password_hash_string,
      user_nick as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      host as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      os_version as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      '' as terminal_imei,
      '' as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      '' as url,
      '' as `domain`,
      '' as relative_url,
      '' as sub_domain,
      '' as super_domain,
      tool_name as tool_name,
      tool_type as tool_type,
      from_id as from_id,
      to_id as to_id,
      '' as from_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      app_version as app_version,
      '' as order_id,
      0 as order_time,
      '' as invite_doce,
      '' as wallet_pwd,
      '' as user_phone,
      bind_phone as bind_phone,
      '' as app_pkg_name,
      '' as group_num,
      deyeMoneyNorm(money) as money,
      '' as sms_code,
      trading_account as trading_account,
      '' as wallet_id,
      '' as address,
      '' as pickup_certificate_type,
      '' as pickup_mobile,
      '' as pickup_name,
      fun_name as fun_name,
      lead_word as lead_word,
      pay_name as pay_name,
      push as push,
      trade_type as trade_type,
      0 as transaction_amount,
      '' as goods_name,
      '' as pay_account,
      '' as reg_account,
      '' as reg_account_type,
      '' as service_provider,
      0 as postal_time,
      0 as goods_num,
      oper_time as oper_time,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      brand as brand,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      message_id as message_id,
      remark as remark,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      '' as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_0033_netbank,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '131')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
    UNION ALL
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, mobile_phone) as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      password_hash_string as password_hash_string,
      user_nick as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      '' as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      os_version as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      '' as terminal_imei,
      '' as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      '' as url,
      '' as `domain`,
      '' as relative_url,
      '' as sub_domain,
      '' as super_domain,
      tool_name as tool_name,
      tool_type as tool_type,
      from_id as from_id,
      '' as to_id,
      from_nickname as from_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      app_version as app_version,
      '' as order_id,
      0 as order_time,
      invite_doce as invite_doce,
      wallet_pwd as wallet_pwd,
      '' as user_phone,
      '' as bind_phone,
      app_pkg_name as app_pkg_name,
      group_num as group_num,
      0 as money,
      sms_code as sms_code,
      '' as trading_account,
      wallet_id as wallet_id,
      '' as address,
      '' as pickup_certificate_type,
      '' as pickup_mobile,
      '' as pickup_name,
      '' as fun_name,
      '' as lead_word,
      '' as pay_name,
      '' as push,
      '' as trade_type,
      0 as transaction_amount,
      '' as goods_name,
      '' as pay_account,
      '' as reg_account,
      '' as reg_account_type,
      '' as service_provider,
      0 as postal_time,
      0 as goods_num,
      0 as oper_time,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      brand as brand,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      '' as message_id,
      '' as remark,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      '' as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_my0035_digcurrency,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '974')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
    UNION ALL
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      '' as password_hash_string,
      '' as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      host as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      os_version as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      terminal_imei as terminal_imei,
      terminal_mac as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      url as url,
      T8.domain_l as `domain`,
      deyeProduceRelativeUrl(url) as relative_url,
      deyeSubDomainNorm(T8.domain_l) as sub_domain,
      deyeSuperDomainNorm(T8.domain_l) as super_domain,
      tool_name as tool_name,
      tool_type as tool_type,
      '' as from_id,
      '' as to_id,
      '' as from_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      app_version as app_version,
      '' as order_id,
      0 as order_time,
      '' as invite_doce,
      '' as wallet_pwd,
      user_phone as user_phone,
      '' as bind_phone,
      '' as app_pkg_name,
      '' as group_num,
      0 as money,
      sms_code as sms_code,
      '' as trading_account,
      '' as wallet_id,
      address as address,
      '' as pickup_certificate_type,
      '' as pickup_mobile,
      pickup_name as pickup_name,
      '' as fun_name,
      '' as lead_word,
      '' as pay_name,
      '' as push,
      '' as trade_type,
      0 as transaction_amount,
      '' as goods_name,
      '' as pay_account,
      '' as reg_account,
      '' as reg_account_type,
      '' as service_provider,
      postal_time as postal_time,
      0 as goods_num,
      0 as oper_time,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      brand as brand,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      '' as message_id,
      remark as remark,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      pickup_certificate_code as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_my0049_financial,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeDomainHandle('', url)) as T8(domain_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '963')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
  ) t1,
  LATERAL TABLE(deyeIpAttributionCompV2(IF(strsrc_ip='', strsrc_ip_v6,strsrc_ip))) as T1(
    src_ip_address_l,
    src_ip_country_l,
    src_ip_province_l,
    src_ip_city_l,
    src_ip_longitude_l,
    src_ip_latitude_l,
    src_ip_country_code_l
  ),
  LATERAL TABLE(deyeIpAttributionCompV2(IF(strdst_ip='', strdst_ip_v6,strdst_ip))) as T2(
    dst_ip_address_l,
    dst_ip_country_l,
    dst_ip_province_l,
    dst_ip_city_l,
    dst_ip_longitude_l,
    dst_ip_latitude_l,
    dst_ip_country_code_l
  )
WHERE (
    CHAR_LENGTH(t1.auth_account) <= 128
  AND CHAR_LENGTH(t1.mobile_phone) <= 30
  AND CHAR_LENGTH(t1.username) <= 512
  AND CHAR_LENGTH(t1.password) <= 512
    );