CREATE SCALAR FUNCTION deyeProduceIpType WITH com.semptian.udf.fieldproduction.DeyeProduceIpType;
CREATE SCALAR FUNCTION deyeVerifyIp WITH com.semptian.udf.verify.DeyeVerifyIp;
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;
CREATE SCALAR FUNCTION deyeUserNameNorm WITH com.semptian.udf.normalization.DeyeUserNameNorm;
CREATE SCALAR FUNCTION deyeMacNorm WITH com.semptian.udf.normalization.DeyeMacNorm;
CREATE SCALAR FUNCTION deyeProduceRelativeUrl WITH com.semptian.udf.fieldproduction.DeyeProduceRelativeUrl;
CREATE SCALAR FUNCTION deyeSubDomainNorm WITH com.semptian.udf.normalization.DeyeSubDomainNorm;
CREATE SCALAR FUNCTION deyePasswordNorm WITH com.semptian.udf.normalization.DeyePasswordNorm;
CREATE SCALAR FUNCTION deyeIpNorm WITH com.semptian.udf.normalization.DeyeIpNorm;
CREATE SCALAR FUNCTION deyeSuperDomainNorm WITH com.semptian.udf.normalization.DeyeSuperDomainNorm;
CREATE SCALAR FUNCTION deyeVerifyTimestamp WITH com.semptian.udf.timestamphandle.DeyeVerifyTimestamp;
CREATE SCALAR FUNCTION deyeCompleteActionTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteActionTypeMap;
CREATE SCALAR FUNCTION deyeCompleteUpareaTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteUpareaTypeMap;
CREATE SCALAR FUNCTION deyeCompleteIspTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteIspTypeMap;
CREATE SCALAR FUNCTION deyeMobilePhoneNorm WITH com.semptian.udf.normalization.DeyeMobilePhoneNorm;
CREATE SCALAR FUNCTION deyeCompleteAuthTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteAuthTypeMap;
CREATE SCALAR FUNCTION deyeCompleteDataTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteDataTypeMap;
CREATE SCALAR FUNCTION deyeCompleteChildTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteChildTypeMap;
CREATE SCALAR FUNCTION deyeCompleteDataSourceMap WITH com.semptian.udf.dimcomplete.DeyeCompleteDataSourceMap;
CREATE SCALAR FUNCTION deyeCompleteProtocolTypeMap WITH com.semptian.udf.dimcomplete.DeyeCompleteProtocolTypeMap;
CREATE SCALAR FUNCTION deyeGetRoamType WITH com.semptian.udf.mark.DeyeGetRoamType;
CREATE SCALAR FUNCTION deyeGetSensitiveArea WITH com.semptian.udf.mark.DeyeGetSensitiveArea;
CREATE SCALAR FUNCTION deyeGetTerroristArea WITH com.semptian.udf.mark.DeyeGetTerroristArea;
CREATE SCALAR FUNCTION deyeGetTimeSpan WITH com.semptian.udf.mark.DeyeGetTimeSpan;
CREATE TABLE FUNCTION deyeIpAttributionComp WITH com.semptian.udtf.dimcomplete.DeyeIpAttributionComp;
CREATE TABLE FUNCTION deyeIpAttributionCompV2 WITH com.semptian.udtf.dimcomplete.DeyeIpAttributionCompV2;
CREATE TABLE FUNCTION deyeAuthAccountHandle WITH com.semptian.udtf.normalization.DeyeAuthAccountHandle;
CREATE TABLE FUNCTION deyeDomainHandle WITH com.semptian.udtf.normalization.DeyeDomainHandle;
CREATE TABLE FUNCTION deyeTimeHandle WITH com.semptian.udtf.normalization.DeyeTimeHandle;
CREATE SCALAR FUNCTION deyeGetIspByPhoneNumber WITH com.semptian.udf.mark.DeyeGetIspByPhoneNumber;
CREATE SCALAR FUNCTION deyeGetCountryCodeByPhoneNumber WITH com.semptian.udf.DeyeGetCountryCodeByPhoneNumber;
CREATE SCALAR FUNCTION deyeUrlDecode WITH com.semptian.udf.fieldspecialhandle.DeyeUrlDecode;
CREATE SCALAR FUNCTION deyeVirtualAccountNorm WITH com.semptian.udf.normalization.DeyeVirtualAccountNorm;
CREATE SCALAR FUNCTION deyeProduceImportantTargetFlag WITH com.semptian.udf.fieldproduction.DeyeProduceImportantTargetFlag;
CREATE SCALAR FUNCTION deyeOsNameNorm WITH com.semptian.udf.normalization.DeyeOsNameNorm;

CREATE TABLE ods_pr_source_0006_game (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_type String,
  proxy_address String,
  proxy_provider String,
  proxy_account String,
  user_nick String,
  from_id String,
  from_nickname String,
  from_role String,
  to_id String,
  to_role String,
  group_num String,
  login_email String,
  login_code String,
  content String,
  bind_phone String,
  sign_name String,
  pay_way String,
  goods_id String,
  goods_num Bigint,
  pickup_certificate_code String,
  user_type String,
  head_url String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  src_ip_area String,
  dst_ip_area String,
  host String,
  longitude Double,
  latitude Double,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  isp_id String,
  device_id String,
  trace_id String,
  stream_end_time Bigint,
  up_teid String,
  down_teid String,
  application_layer_protocol String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  terminal_imei String,
  terminal_imsi String,
  username String,
  user_id String,
  password String,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_text String,
  attach_num Integer,
  keywords String,
  attach_download_path String,
  file_path String,
  file_size Integer,
  file_id String,
  tool_type String,
  tool_name String,
  local_action String,
  mac String,
  hardware_type String,
  hardware_sign String,
  terminal_mac String,
  os_name String,
  os_version String,
  session_id String,
  pickup_name String,
  icp_provider String,
  rule_version String,
  record_id String,
  soft_name String,
  favorite_tags String,
  host_url_tag String,
  to_nickname String,
  model String,
  app_version String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_0006_game',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_entertainment',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE ods_pr_source_0066_live (
  data_type String,
  data_source String,
  protocol_type String,
  child_type String,
  `action` String,
  auth_type String,
  auth_account String,
  proxy_type String,
  proxy_address String,
  proxy_provider String,
  proxy_account String,
  strsrc_ip String,
  strdst_ip String,
  src_port Integer,
  dst_port Integer,
  strsrc_ip_v6 String,
  strdst_ip_v6 String,
  src_port_v6 Integer,
  dst_port_v6 Integer,
  src_ip_area String,
  dst_ip_area String,
  referer String,
  pickup_name String,
  group_name String,
  regis_time Bigint,
  host String,
  user_nick String,
  from_id String,
  to_id String,
  group_num String,
  content String,
  user_type String,
  pickup_mobile String,
  pickup_certificate_type String,
  pickup_certificate_code String,
  lb_account_id String,
  part_type String,
  other_room_id String,
  description String,
  live_time String,
  hot_top String,
  admin_id String,
  user_id String,
  video_id String,
  channel_url String,
  video_name String,
  video_desc String,
  video_room String,
  topic_id String,
  in_time Bigint,
  city String,
  message String,
  out_time Bigint,
  login_time Bigint,
  video_count String,
  counter Bigint,
  file_name String,
  app_pkg_name String,
  app_name String,
  head_url String,
  friend_head_url String,
  room_channel String,
  longitude Double,
  latitude Double,
  base_station_id String,
  ownership_land String,
  internet_land String,
  uparea_id String,
  lang_type String,
  abstract String,
  subject String,
  text String,
  attach_text String,
  keywords String,
  attach_names String,
  attach_sizes String,
  attach_md5s String,
  attach_num Integer,
  attach_download_path String,
  file_size Integer,
  file_path String,
  file_id String,
  tool_type String,
  tool_name String,
  isp_id String,
  device_id String,
  trace_id String,
  stream_end_time Bigint,
  up_teid String,
  down_teid String,
  application_layer_protocol String,
  tunnel_type String,
  imsi String,
  imei String,
  associate_mobile String,
  password String,
  username String,
  url String,
  `domain` String,
  local_action String,
  mac String,
  hardware_type String,
  hardware_sign String,
  os_name String,
  os_version String,
  session_id String,
  icp_provider String,
  rule_version String,
  record_id String,
  soft_name String,
  favorite_tags String,
  host_url_tag String,
  from_nickname String,
  model String,
  to_nickname String,
  capture_time Bigint,
  insert_time Bigint,
  data_id String,
  extend_column String
) WITH (
  'type' = 'kafka',
  'topic' = 'ods_pr_source_0066_live',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'group.id' = 'dwd_pr_entertainment',
  'security.mode.flag' = 'false',
  'session.timeout.ms' = '30000',
  'enable.auto.commit' = 'false',
  'auto.offset.reset' = 'latest',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000',
    'parallelism' = '8',
  'format.type' = 'avro'
);
CREATE TABLE dwd_pr_entertainment (
  data_type String,
  data_type_map String,
  child_type String,
  child_type_map String,
  `action` String,
  action_map String,
  auth_account String,
  auth_type String,
  auth_type_map String,
  main_account String,
  data_source String,
  data_source_map String,
  mobile_phone String,
  uparea_id String,
  uparea_id_map String,
  username String,
  password String,
  user_nick String,
  user_id String,
  imei String,
  imsi String,
  base_station_id String,
  isp_id String,
  isp_id_map String,
  internet_land String,
  ownership_land String,
  application_layer_protocol String,
  down_teid String,
  tunnel_type String,
  up_teid String,
  protocol_type String,
  protocol_type_map String,
  strsrc_ip String,
  strsrc_ip_v6 String,
  strdst_ip String,
  strdst_ip_v6 String,
  dst_port Integer,
  dst_port_v6 Integer,
  src_port Integer,
  src_port_v6 Integer,
  src_ip_type Integer,
  src_ip_country String,
  src_ip_province String,
  src_ip_city String,
  src_ip_address String,
  src_ip_longitude Double,
  src_ip_latitude Double,
  dst_ip_type Integer,
  dst_ip_country String,
  dst_ip_province String,
  dst_ip_city String,
  dst_ip_address String,
  dst_ip_longitude Double,
  dst_ip_latitude Double,
  host String,
  hardware_sign String,
  hardware_type String,
  local_action String,
  mac String,
  os_name String,
  os_version String,
  terminal_type String,
  terminal_type_map String,
  terminal_imei String,
  terminal_imsi String,
  terminal_mac String,
  file_id String,
  file_path String,
  file_size Integer,
  attach_num Integer,
  attach_names String,
  attach_sizes String,
  attach_download_path String,
  attach_md5s String,
  attach_text String,
  subject String,
  keywords String,
  text String,
  lang_type String,
  content String,
  message String,
  url String,
  `domain` String,
  relative_url String,
  sub_domain String,
  super_domain String,
  app_name String,
  tool_name String,
  tool_type String,
  from_id String,
  to_id String,
  from_role String,
  from_nickname String,
  to_role String,
  to_nickname String,
  from_account String,
  from_account_remark String,
  to_account String,
  to_account_remark String,
  data_id String,
  capture_time Bigint,
  capture_day String,
  capture_hour Integer,
  insert_time Bigint,
  mark String,
  device_id String,
  trace_id String,
  app_version String,
  goods_id String,
  pay_way String,
  user_type String,
  video_id String,
  video_room String,
  bind_phone String,
  login_code String,
  referer String,
  app_pkg_name String,
  city String,
  description String,
  friend_head_url String,
  group_name String,
  group_num String,
  head_url String,
  sign_name String,
  topic_id String,
  admin_id String,
  channel_url String,
  counter Bigint,
  hot_top String,
  in_time Bigint,
  lb_account_id String,
  live_time String,
  login_time Bigint,
  other_room_id String,
  out_time Bigint,
  part_type String,
  pickup_certificate_type String,
  pickup_mobile String,
  regis_time Bigint,
  room_channel String,
  video_name String,
  login_email String,
  pickup_name String,
  file_name String,
  video_count String,
  video_desc String,
  goods_num Bigint,
  proxy_account String,
  proxy_address String,
  proxy_provider String,
  proxy_type String,
  latitude Double,
  longitude Double,
  abstract String,
  favorite_tags String,
  host_url_tag String,
  icp_provider String,
  session_id String,
  soft_name String,
  stream_end_time Bigint,
  model String,
  pickup_certificate_code String,
  entity_list String,
  province_attribution String,
  time_span String,
  number_risk_level String,
  radius_risk String,
  roam_type String,
  terrorist_area String,
  sensitive_area String,
  format_virtual_account String,
  format_username String,
  norm_data_type String,
  important_target_flag Integer
) WITH (
  'type' = 'kafka',
  'topic' = 'v64_dwd_pr_entertainment',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'security.mode.flag' = 'false',
  'format.type' = 'avro',
  'batch.size'='1048576',
  'acks'='1',
  'linger.ms'='100',
  'buffer.memory'='33554432',
  'retries'='1',
  'feature.max.request.size' = '52428800'
);

CREATE TABLE dwd_pr_tmp (
  data_type String,
  data_type_map String,
  auth_account String,
  mobile_phone String,
  username String,
  password String,
  data_id String,
  capture_time Bigint,
  capture_day String,
  capture_hour Integer,
  insert_time Bigint
) WITH (
  'type' = 'kafka',
  'topic' = 'v64_dwd_pr_tmp',
  'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
  'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
  'security.mode.flag' = 'false',
  'format.type' = 'json',
  'batch.size'='1048576',
  'acks'='1',
  'linger.ms'='100',
  'buffer.memory'='33554432',
  'retries'='1',
  'feature.max.request.size' = '52428800'
  );

INSERT INTO
    dwd_pr_tmp
SELECT
    t1.data_type as data_type,
    deyeCompleteDataTypeMap(t1.data_type, true)[2] as data_type_map,
    t1.auth_account as auth_account,
    t1.mobile_phone as mobile_phone,
    t1.username as username,
    t1.password as password,
    t1.data_id as data_id,
    t1.capture_time as capture_time,
    t1.capture_day as capture_day,
    t1.capture_hour as capture_hour,
    t1.insert_time as insert_time
FROM
    (
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            user_nick as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
                WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
                ELSE ''
                END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
                WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
                ELSE ''
                END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            host as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            os_version as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            terminal_imei as terminal_imei,
            terminal_imsi as terminal_imsi,
            terminal_mac as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            '' as message,
            '' as url,
            '' as `domain`,
            '' as relative_url,
            '' as sub_domain,
            '' as super_domain,
            '' as app_name,
            tool_name as tool_name,
            tool_type as tool_type,
            from_id as from_id,
            to_id as to_id,
            from_role as from_role,
            from_nickname as from_nickname,
            to_role as to_role,
            to_nickname as to_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            app_version as app_version,
            goods_id as goods_id,
            pay_way as pay_way,
            user_type as user_type,
            '' as video_id,
            '' as video_room,
            bind_phone as bind_phone,
            login_code as login_code,
            '' as referer,
            '' as app_pkg_name,
            '' as city,
            '' as description,
            '' as friend_head_url,
            '' as group_name,
            group_num as group_num,
            head_url as head_url,
            sign_name as sign_name,
            '' as topic_id,
            '' as admin_id,
            '' as channel_url,
            0 as counter,
            '' as hot_top,
            0 as in_time,
            '' as lb_account_id,
            '' as live_time,
            0 as login_time,
            '' as other_room_id,
            0 as out_time,
            '' as part_type,
            '' as pickup_certificate_type,
            '' as pickup_mobile,
            0 as regis_time,
            '' as room_channel,
            '' as video_name,
            login_email as login_email,
            pickup_name as pickup_name,
            '' as file_name,
            '' as video_count,
            '' as video_desc,
            goods_num as goods_num,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            pickup_certificate_code as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_0006_game,
            LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '104')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
        UNION ALL
        SELECT
            data_type as data_type,
            deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
            deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
            deyeCompleteActionTypeMap(`action`)[1] as `action`,
            deyeCompleteActionTypeMap(`action`)[2] as action_map,
            T3.auth_account_l as auth_account,
            T3.auth_type_l as auth_type,
            deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
            '' as main_account,
            data_source as data_source,
            deyeCompleteDataSourceMap(data_source) as data_source_map,
            deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
            uparea_id as uparea_id,
            deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
            deyeUserNameNorm(username) as username,
            deyePasswordNorm(password) as password,
            user_nick as user_nick,
            user_id as user_id,
            imei as imei,
            imsi as imsi,
            base_station_id as base_station_id,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as isp_id,
            deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
            internet_land as internet_land,
            CASE
            WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
            ELSE ''
            END as ownership_land,
            application_layer_protocol as application_layer_protocol,
            down_teid as down_teid,
            tunnel_type as tunnel_type,
            up_teid as up_teid,
            protocol_type as protocol_type,
            deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
            deyeIpNorm(strsrc_ip) as strsrc_ip,
            deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
            deyeIpNorm(strdst_ip) as strdst_ip,
            deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
            dst_port as dst_port,
            dst_port_v6 as dst_port_v6,
            src_port as src_port,
            src_port_v6 as src_port_v6,
            deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
            deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
            host as host,
            hardware_sign as hardware_sign,
            hardware_type as hardware_type,
            local_action as local_action,
            deyeMacNorm(mac) as mac,
            os_name as os_name,
            os_version as os_version,
            '' as terminal_type,
            '' as terminal_type_map,
            '' as terminal_imei,
            '' as terminal_imsi,
            '' as terminal_mac,
            file_id as file_id,
            file_path as file_path,
            file_size as file_size,
            attach_num as attach_num,
            attach_names as attach_names,
            attach_sizes as attach_sizes,
            attach_download_path as attach_download_path,
            attach_md5s as attach_md5s,
            attach_text as attach_text,
            subject as subject,
            keywords as keywords,
            text as text,
            lang_type as lang_type,
            content as content,
            message as message,
            url as url,
            T8.domain_l as `domain`,
            deyeProduceRelativeUrl(url) as relative_url,
            deyeSubDomainNorm(T8.domain_l) as sub_domain,
            deyeSuperDomainNorm(T8.domain_l) as super_domain,
            '' as app_name,
            tool_name as tool_name,
            tool_type as tool_type,
            from_id as from_id,
            to_id as to_id,
            '' as from_role,
            from_nickname as from_nickname,
            '' as to_role,
            to_nickname as to_nickname,
            '' as from_account,
            '' as from_account_remark,
            '' as to_account,
            '' as to_account_remark,
            data_id as data_id,
            capture_time as capture_time,
            T9.capture_day_l as capture_day,
            T9.capture_hour_l as capture_hour,
            deyeTimestampConverter(data_id) as insert_time,
            '' as mark,
            device_id as device_id,
            trace_id as trace_id,
            '' as app_version,
            '' as goods_id,
            '' as pay_way,
            user_type as user_type,
            video_id as video_id,
            video_room as video_room,
            '' as bind_phone,
            '' as login_code,
            referer as referer,
            app_pkg_name as app_pkg_name,
            city as city,
            description as description,
            friend_head_url as friend_head_url,
            group_name as group_name,
            group_num as group_num,
            head_url as head_url,
            '' as sign_name,
            topic_id as topic_id,
            admin_id as admin_id,
            channel_url as channel_url,
            counter as counter,
            hot_top as hot_top,
            in_time as in_time,
            lb_account_id as lb_account_id,
            live_time as live_time,
            login_time as login_time,
            other_room_id as other_room_id,
            out_time as out_time,
            part_type as part_type,
            pickup_certificate_type as pickup_certificate_type,
            pickup_mobile as pickup_mobile,
            regis_time as regis_time,
            room_channel as room_channel,
            video_name as video_name,
            '' as login_email,
            pickup_name as pickup_name,
            file_name as file_name,
            video_count as video_count,
            video_desc as video_desc,
            0 as goods_num,
            proxy_account as proxy_account,
            proxy_address as proxy_address,
            proxy_provider as proxy_provider,
            proxy_type as proxy_type,
            latitude as latitude,
            longitude as longitude,
            abstract as abstract,
            favorite_tags as favorite_tags,
            host_url_tag as host_url_tag,
            icp_provider as icp_provider,
            session_id as session_id,
            soft_name as soft_name,
            stream_end_time as stream_end_time,
            model as model,
            pickup_certificate_code as pickup_certificate_code,
            '' as entity_list,
            '' as province_attribution,
            deyeGetTimeSpan(capture_time) as time_span,
            '' as number_risk_level,
            '' as radius_risk,
            '' as roam_type
        FROM
            ods_pr_source_0066_live,
            LATERAL TABLE(
            deyeAuthAccountHandle(
            auth_type,
            auth_account,
            data_type,
            deyeIpNorm(strsrc_ip),
            deyeIpNorm(strsrc_ip_v6),
            deyeIpNorm(strdst_ip),
            deyeIpNorm(strdst_ip_v6),
            capture_time
            )
            ) as T3(auth_type_l, auth_account_l),
            LATERAL TABLE(deyeDomainHandle(`domain`, url)) as T8(domain_l),
            LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
        WHERE
            (
            (data_type = '155')
          AND (deyeVerifyTimestamp(capture_time, -2) = '1')
          AND (deyeVerifyTimestamp(capture_time, 1) = '0')
          AND (
            deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
            )
          AND (
            deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
            )
            )
    ) t1
WHERE (
    CHAR_LENGTH(t1.auth_account) > 128
  OR CHAR_LENGTH(t1.mobile_phone) > 30
  OR CHAR_LENGTH(t1.username) > 512
  OR CHAR_LENGTH(t1.password) > 512
    );

INSERT INTO
  dwd_pr_entertainment
SELECT
  t1.data_type as data_type,
  deyeCompleteDataTypeMap(t1.data_type, true)[2] as data_type_map,
  t1.child_type as child_type,
  t1.child_type_map as child_type_map,
  t1. `action` as `action`,
  t1.action_map as action_map,
  t1.auth_account as auth_account,
  t1.auth_type as auth_type,
  t1.auth_type_map as auth_type_map,
  t1.main_account as main_account,
  t1.data_source as data_source,
  t1.data_source_map as data_source_map,
  t1.mobile_phone as mobile_phone,
  t1.uparea_id as uparea_id,
  t1.uparea_id_map as uparea_id_map,
  t1.username as username,
  t1.password as password,
  t1.user_nick as user_nick,
  t1.user_id as user_id,
  t1.imei as imei,
  t1.imsi as imsi,
  t1.base_station_id as base_station_id,
  t1.isp_id as isp_id,
  t1.isp_id_map as isp_id_map,
  t1.internet_land as internet_land,
  t1.ownership_land as ownership_land,
  t1.application_layer_protocol as application_layer_protocol,
  t1.down_teid as down_teid,
  t1.tunnel_type as tunnel_type,
  t1.up_teid as up_teid,
  t1.protocol_type as protocol_type,
  t1.protocol_type_map as protocol_type_map,
  t1.strsrc_ip as strsrc_ip,
  t1.strsrc_ip_v6 as strsrc_ip_v6,
  t1.strdst_ip as strdst_ip,
  t1.strdst_ip_v6 as strdst_ip_v6,
  t1.dst_port as dst_port,
  t1.dst_port_v6 as dst_port_v6,
  t1.src_port as src_port,
  t1.src_port_v6 as src_port_v6,
  t1.src_ip_type as src_ip_type,
  T1.src_ip_country_l as src_ip_country,
  T1.src_ip_province_l as src_ip_province,
  T1.src_ip_city_l as src_ip_city,
  T1.src_ip_address_l as src_ip_address,
  T1.src_ip_longitude_l as src_ip_longitude,
  T1.src_ip_latitude_l as src_ip_latitude,
  t1.dst_ip_type as dst_ip_type,
  T2.dst_ip_country_l as dst_ip_country,
  T2.dst_ip_province_l as dst_ip_province,
  T2.dst_ip_city_l as dst_ip_city,
  T2.dst_ip_address_l as dst_ip_address,
  T2.dst_ip_longitude_l as dst_ip_longitude,
  T2.dst_ip_latitude_l as dst_ip_latitude,
  case
    when position(':' in t1.host)>0 then substring(t1.host,1,position(':' in t1.host) -1)
    else t1.host
  end as host,
  t1.hardware_sign as hardware_sign,
  t1.hardware_type as hardware_type,
  t1.local_action as local_action,
  t1.mac as mac,
  deyeOsNameNorm(t1.os_name) as os_name,
  t1.os_version as os_version,
  t1.terminal_type as terminal_type,
  t1.terminal_type_map as terminal_type_map,
  t1.terminal_imei as terminal_imei,
  t1.terminal_imsi as terminal_imsi,
  t1.terminal_mac as terminal_mac,
  t1.file_id as file_id,
  t1.file_path as file_path,
  t1.file_size as file_size,
  t1.attach_num as attach_num,
  t1.attach_names as attach_names,
  t1.attach_sizes as attach_sizes,
  t1.attach_download_path as attach_download_path,
  t1.attach_md5s as attach_md5s,
  t1.attach_text as attach_text,
  t1.subject as subject,
  t1.keywords as keywords,
  t1.text as text,
  SPLIT_INDEX(IF(LEFT(t1.lang_type,1)='[' AND RIGHT(t1.lang_type,1)=']', SUBSTR(t1.lang_type,2,CHAR_LENGTH(t1.lang_type)-2), t1.lang_type),' ',0) as lang_type,
  t1.content as content,
  t1.message as message,
  deyeUrlDecode(t1.url) as url,
  t1. `domain` as `domain`,
  deyeUrlDecode(t1.relative_url) as relative_url,
  t1.sub_domain as sub_domain,
  t1.super_domain as super_domain,
  t1.app_name as app_name,
  t1.child_type_map as tool_name,
  t1.child_type as tool_type,
  t1.from_id as from_id,
  t1.to_id as to_id,
  t1.from_role as from_role,
  t1.from_nickname as from_nickname,
  t1.to_role as to_role,
  t1.to_nickname as to_nickname,
  t1.from_account as from_account,
  t1.from_account_remark as from_account_remark,
  t1.to_account as to_account,
  t1.to_account_remark as to_account_remark,
  t1.data_id as data_id,
  t1.capture_time as capture_time,
  t1.capture_day as capture_day,
  t1.capture_hour as capture_hour,
  t1.insert_time as insert_time,
  t1.mark as mark,
  t1.device_id as device_id,
  t1.trace_id as trace_id,
  t1.app_version as app_version,
  t1.goods_id as goods_id,
  t1.pay_way as pay_way,
  t1.user_type as user_type,
  t1.video_id as video_id,
  t1.video_room as video_room,
  t1.bind_phone as bind_phone,
  t1.login_code as login_code,
  t1.referer as referer,
  t1.app_pkg_name as app_pkg_name,
  t1.city as city,
  t1.description as description,
  t1.friend_head_url as friend_head_url,
  t1.group_name as group_name,
  t1.group_num as group_num,
  t1.head_url as head_url,
  t1.sign_name as sign_name,
  t1.topic_id as topic_id,
  t1.admin_id as admin_id,
  t1.channel_url as channel_url,
  t1.counter as counter,
  t1.hot_top as hot_top,
  t1.in_time as in_time,
  t1.lb_account_id as lb_account_id,
  t1.live_time as live_time,
  t1.login_time as login_time,
  t1.other_room_id as other_room_id,
  t1.out_time as out_time,
  t1.part_type as part_type,
  t1.pickup_certificate_type as pickup_certificate_type,
  t1.pickup_mobile as pickup_mobile,
  t1.regis_time as regis_time,
  t1.room_channel as room_channel,
  t1.video_name as video_name,
  t1.login_email as login_email,
  t1.pickup_name as pickup_name,
  t1.file_name as file_name,
  t1.video_count as video_count,
  t1.video_desc as video_desc,
  t1.goods_num as goods_num,
  t1.proxy_account as proxy_account,
  t1.proxy_address as proxy_address,
  t1.proxy_provider as proxy_provider,
  t1.proxy_type as proxy_type,
  t1.latitude as latitude,
  t1.longitude as longitude,
  t1.abstract as abstract,
  t1.favorite_tags as favorite_tags,
  t1.host_url_tag as host_url_tag,
  t1.icp_provider as icp_provider,
  t1.session_id as session_id,
  t1.soft_name as soft_name,
  t1.stream_end_time as stream_end_time,
  t1.model as model,
  t1.pickup_certificate_code as pickup_certificate_code,
  t1.entity_list as entity_list,
  t1.province_attribution as province_attribution,
  t1.time_span as time_span,
  t1.number_risk_level as number_risk_level,
  t1.radius_risk as radius_risk,
  t1.roam_type as roam_type,
  deyeGetTerroristArea(
    deyeGetCountryCodeByPhoneNumber(t1.auth_account),
    'DZ',
    T1.src_ip_country_code_l
  ) as terrorist_area,
  deyeGetSensitiveArea(
    deyeGetCountryCodeByPhoneNumber(t1.auth_account),
    'DZ',
    T1.src_ip_country_code_l
  ) as sensitive_area,
  '' AS format_virtual_account,
  LOWER(t1.username) as format_username,
  deyeCompleteDataTypeMap(t1.data_type, true)[1] as norm_data_type,
  deyeProduceImportantTargetFlag(data_type,t1.auth_account,t1.auth_type,deyeIpNorm(strsrc_ip),deyeIpNorm(strsrc_ip_v6),deyeIpNorm(strdst_ip),deyeIpNorm(strdst_ip_v6)) as important_target_flag
FROM
  (
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      user_nick as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      host as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      os_version as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      terminal_imei as terminal_imei,
      terminal_imsi as terminal_imsi,
      terminal_mac as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      '' as message,
      '' as url,
      '' as `domain`,
      '' as relative_url,
      '' as sub_domain,
      '' as super_domain,
      '' as app_name,
      tool_name as tool_name,
      tool_type as tool_type,
      from_id as from_id,
      to_id as to_id,
      from_role as from_role,
      from_nickname as from_nickname,
      to_role as to_role,
      to_nickname as to_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      app_version as app_version,
      goods_id as goods_id,
      pay_way as pay_way,
      user_type as user_type,
      '' as video_id,
      '' as video_room,
      bind_phone as bind_phone,
      login_code as login_code,
      '' as referer,
      '' as app_pkg_name,
      '' as city,
      '' as description,
      '' as friend_head_url,
      '' as group_name,
      group_num as group_num,
      head_url as head_url,
      sign_name as sign_name,
      '' as topic_id,
      '' as admin_id,
      '' as channel_url,
      0 as counter,
      '' as hot_top,
      0 as in_time,
      '' as lb_account_id,
      '' as live_time,
      0 as login_time,
      '' as other_room_id,
      0 as out_time,
      '' as part_type,
      '' as pickup_certificate_type,
      '' as pickup_mobile,
      0 as regis_time,
      '' as room_channel,
      '' as video_name,
      login_email as login_email,
      pickup_name as pickup_name,
      '' as file_name,
      '' as video_count,
      '' as video_desc,
      goods_num as goods_num,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      pickup_certificate_code as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_0006_game,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '104')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
    UNION ALL
    SELECT
      data_type as data_type,
      deyeCompleteChildTypeMap(child_type, data_type)[1] as child_type,
      deyeCompleteChildTypeMap(child_type, data_type)[2] as child_type_map,
      deyeCompleteActionTypeMap(`action`)[1] as `action`,
      deyeCompleteActionTypeMap(`action`)[2] as action_map,
      T3.auth_account_l as auth_account,
      T3.auth_type_l as auth_type,
      deyeCompleteAuthTypeMap(T3.auth_type_l) as auth_type_map,
      '' as main_account,
      data_source as data_source,
      deyeCompleteDataSourceMap(data_source) as data_source_map,
      deyeMobilePhoneNorm(associate_mobile, '') as mobile_phone,
      uparea_id as uparea_id,
      deyeCompleteUpareaTypeMap(uparea_id) as uparea_id_map,
      deyeUserNameNorm(username) as username,
      deyePasswordNorm(password) as password,
      user_nick as user_nick,
      user_id as user_id,
      imei as imei,
      imsi as imsi,
      base_station_id as base_station_id,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetIspByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as isp_id,
      deyeCompleteIspTypeMap(CASE WHEN(auth_type = '1020004') THEN deyeGetIspByPhoneNumber(T3.auth_account_l) ELSE '' END) as isp_id_map,
      internet_land as internet_land,
      CASE
        WHEN auth_type = '1020004' THEN deyeGetCountryCodeByPhoneNumber(T3.auth_account_l)
        ELSE ''
      END as ownership_land,
      application_layer_protocol as application_layer_protocol,
      down_teid as down_teid,
      tunnel_type as tunnel_type,
      up_teid as up_teid,
      protocol_type as protocol_type,
      deyeCompleteProtocolTypeMap(protocol_type) as protocol_type_map,
      deyeIpNorm(strsrc_ip) as strsrc_ip,
      deyeIpNorm(strsrc_ip_v6) as strsrc_ip_v6,
      deyeIpNorm(strdst_ip) as strdst_ip,
      deyeIpNorm(strdst_ip_v6) as strdst_ip_v6,
      dst_port as dst_port,
      dst_port_v6 as dst_port_v6,
      src_port as src_port,
      src_port_v6 as src_port_v6,
      deyeProduceIpType(strsrc_ip, strsrc_ip_v6) as src_ip_type,
      deyeProduceIpType(strdst_ip, strdst_ip_v6) as dst_ip_type,
      host as host,
      hardware_sign as hardware_sign,
      hardware_type as hardware_type,
      local_action as local_action,
      deyeMacNorm(mac) as mac,
      os_name as os_name,
      os_version as os_version,
      '' as terminal_type,
      '' as terminal_type_map,
      '' as terminal_imei,
      '' as terminal_imsi,
      '' as terminal_mac,
      file_id as file_id,
      file_path as file_path,
      file_size as file_size,
      attach_num as attach_num,
      attach_names as attach_names,
      attach_sizes as attach_sizes,
      attach_download_path as attach_download_path,
      attach_md5s as attach_md5s,
      attach_text as attach_text,
      subject as subject,
      keywords as keywords,
      text as text,
      lang_type as lang_type,
      content as content,
      message as message,
      url as url,
      T8.domain_l as `domain`,
      deyeProduceRelativeUrl(url) as relative_url,
      deyeSubDomainNorm(T8.domain_l) as sub_domain,
      deyeSuperDomainNorm(T8.domain_l) as super_domain,
      '' as app_name,
      tool_name as tool_name,
      tool_type as tool_type,
      from_id as from_id,
      to_id as to_id,
      '' as from_role,
      from_nickname as from_nickname,
      '' as to_role,
      to_nickname as to_nickname,
      '' as from_account,
      '' as from_account_remark,
      '' as to_account,
      '' as to_account_remark,
      data_id as data_id,
      capture_time as capture_time,
      T9.capture_day_l as capture_day,
      T9.capture_hour_l as capture_hour,
      deyeTimestampConverter(data_id) as insert_time,
      '' as mark,
      device_id as device_id,
      trace_id as trace_id,
      '' as app_version,
      '' as goods_id,
      '' as pay_way,
      user_type as user_type,
      video_id as video_id,
      video_room as video_room,
      '' as bind_phone,
      '' as login_code,
      referer as referer,
      app_pkg_name as app_pkg_name,
      city as city,
      description as description,
      friend_head_url as friend_head_url,
      group_name as group_name,
      group_num as group_num,
      head_url as head_url,
      '' as sign_name,
      topic_id as topic_id,
      admin_id as admin_id,
      channel_url as channel_url,
      counter as counter,
      hot_top as hot_top,
      in_time as in_time,
      lb_account_id as lb_account_id,
      live_time as live_time,
      login_time as login_time,
      other_room_id as other_room_id,
      out_time as out_time,
      part_type as part_type,
      pickup_certificate_type as pickup_certificate_type,
      pickup_mobile as pickup_mobile,
      regis_time as regis_time,
      room_channel as room_channel,
      video_name as video_name,
      '' as login_email,
      pickup_name as pickup_name,
      file_name as file_name,
      video_count as video_count,
      video_desc as video_desc,
      0 as goods_num,
      proxy_account as proxy_account,
      proxy_address as proxy_address,
      proxy_provider as proxy_provider,
      proxy_type as proxy_type,
      latitude as latitude,
      longitude as longitude,
      abstract as abstract,
      favorite_tags as favorite_tags,
      host_url_tag as host_url_tag,
      icp_provider as icp_provider,
      session_id as session_id,
      soft_name as soft_name,
      stream_end_time as stream_end_time,
      model as model,
      pickup_certificate_code as pickup_certificate_code,
      '' as entity_list,
      '' as province_attribution,
      deyeGetTimeSpan(capture_time) as time_span,
      '' as number_risk_level,
      '' as radius_risk,
      '' as roam_type
    FROM
      ods_pr_source_0066_live,
      LATERAL TABLE(
        deyeAuthAccountHandle(
          auth_type,
          auth_account,
          data_type,
          deyeIpNorm(strsrc_ip),
          deyeIpNorm(strsrc_ip_v6),
          deyeIpNorm(strdst_ip),
          deyeIpNorm(strdst_ip_v6),
          capture_time
        )
      ) as T3(auth_type_l, auth_account_l),
      LATERAL TABLE(deyeDomainHandle(`domain`, url)) as T8(domain_l),
      LATERAL TABLE(deyeTimeHandle(capture_time)) as T9(capture_day_l, capture_hour_l)
    WHERE
      (
        (data_type = '155')
        AND (deyeVerifyTimestamp(capture_time, -2) = '1')
        AND (deyeVerifyTimestamp(capture_time, 1) = '0')
        AND (
          deyeVerifyIp(strsrc_ip, strsrc_ip_v6) = '1'
        )
        AND (
          deyeVerifyIp(strdst_ip, strdst_ip_v6) = '1'
        )
      )
  ) t1,
  LATERAL TABLE(deyeIpAttributionCompV2(IF(strsrc_ip='', strsrc_ip_v6,strsrc_ip))) as T1(
    src_ip_address_l,
    src_ip_country_l,
    src_ip_province_l,
    src_ip_city_l,
    src_ip_longitude_l,
    src_ip_latitude_l,
    src_ip_country_code_l
  ),
  LATERAL TABLE(deyeIpAttributionCompV2(IF(strdst_ip='', strdst_ip_v6,strdst_ip))) as T2(
    dst_ip_address_l,
    dst_ip_country_l,
    dst_ip_province_l,
    dst_ip_city_l,
    dst_ip_longitude_l,
    dst_ip_latitude_l,
    dst_ip_country_code_l
  )
WHERE (
    CHAR_LENGTH(t1.auth_account) <= 128
    AND CHAR_LENGTH(t1.mobile_phone) <= 30
    AND CHAR_LENGTH(t1.username) <= 512
    AND CHAR_LENGTH(t1.password) <= 512
    );