---
# CBP业务系统IP映射配置文件
# 定义需要批量替换的IP地址映射关系
# 注意: IP按从大到小排序，避免部分替换问题

# IP映射列表 - 按IP地址从大到小排序
ip_mappings:
  # Redis服务器
  - old_ip: "192.168.13.79"
    new_ip: "192.168.28.20"
    description: "redis-s2 Redis缓存服务器"
    service_type: "redis"
    
  - old_ip: "192.168.13.78"
    new_ip: "192.168.28.19"
    description: "redis-s1 Redis缓存服务器"
    service_type: "redis"
    
  # AI服务器
  - old_ip: "192.168.13.31"
    new_ip: "192.168.28.18"
    description: "app-s22 AI服务器"
    service_type: "ai"
    
  - old_ip: "192.168.13.30"
    new_ip: "192.168.28.17"
    description: "app-s21 AI服务器"
    service_type: "ai"
    
  # 应用服务器
  - old_ip: "192.168.13.17"
    new_ip: "192.168.28.16"
    description: "app-s12 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.16"
    new_ip: "192.168.28.15"
    description: "app-s11 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.15"
    new_ip: "192.168.28.14"
    description: "app-s10 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.14"
    new_ip: "192.168.28.13"
    description: "app-s9 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.13"
    new_ip: "192.168.28.12"
    description: "app-s8 应用服务器/NF信息中心"
    service_type: "app"
    
  - old_ip: "192.168.13.12"
    new_ip: "192.168.28.11"
    description: "app-s7 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.11"
    new_ip: "192.168.28.10"
    description: "app-s6 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.10"
    new_ip: "192.168.28.9"
    description: "app-s5 应用服务器/公共组件/前端"
    service_type: "app"
    
  - old_ip: "192.168.13.9"
    new_ip: "192.168.28.8"
    description: "app-s4 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.8"
    new_ip: "192.168.28.7"
    description: "app-s3 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.7"
    new_ip: "192.168.28.6"
    description: "app-s2 应用服务器"
    service_type: "app"
    
  - old_ip: "192.168.13.6"
    new_ip: "192.168.28.25"
    description: "客户端服务器/调度中心"
    service_type: "client"
    
  - old_ip: "192.168.13.5"
    new_ip: "192.168.28.5"
    description: "oracle-s1 Oracle数据库服务器"
    service_type: "database"
    
  - old_ip: "192.168.13.4"
    new_ip: "192.168.28.4"
    description: "mysql-s1 MySQL数据库服务器"
    service_type: "database"
    
  - old_ip: "192.168.13.3"
    new_ip: "192.168.28.3"
    description: "nebula-s3 Nebula图数据库服务器"
    service_type: "nebula"
    
  - old_ip: "192.168.13.2"
    new_ip: "192.168.28.2"
    description: "nebula-s2 Nebula图数据库服务器"
    service_type: "nebula"
    
  - old_ip: "192.168.13.1"
    new_ip: "192.168.28.1"
    description: "nebula-s1 Nebula图数据库服务器"
    service_type: "nebula"

# 目标服务器组
target_server_groups:
  - cbp_all_servers
  - nginx_servers

# 配置文件搜索路径
config_search_paths:
  - "/opt/nginx-1.10.3/conf"
  - "/etc/nginx"
  - "/semptian/web"
  - "/data1/semptian/service"
  - "/opt/cbp"
  - "/etc/cbp"

# 配置文件匹配模式
config_file_patterns:
  - "*.conf"
  - "*.config"
  - "*.properties"
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.js"
  - "*.html"
  - "*.xml"

# 备份配置
backup_base_dir: "/tmp/cbp_ip_change_backup"
backup_retention_days: 30

# Nginx相关配置
nginx_config_paths:
  - "/opt/nginx-1.10.3/conf/nginx.conf"
  - "/etc/nginx/nginx.conf"
  - "/opt/nginx-1.10.3/conf/conf.d"
  - "/etc/nginx/conf.d"

# 前端配置路径
frontend_config_paths:
  - "/semptian/web"
  - "/opt/cbp/web"

# 服务重启配置
services_to_restart:
  - nginx
  - cbp-portal
  - cbp-gateway

# 验证配置
health_check_urls:
  - "http://192.168.28.9:8104/#/home"  # CBP登录页面
  - "http://192.168.28.9:8848/nacos"   # Nacos控制台
  - "http://192.168.28.9:9100/filecenter"  # 文件服务

# 排除的文件和目录
exclude_patterns:
  - "*.log"
  - "*.tmp"
  - "*.bak"
  - "*.backup"
  - "*~"
  - ".git/*"
  - "node_modules/*"
  - "target/*"
  - "build/*"

# 特殊处理的配置文件
special_files:
  - path: "/opt/nginx-1.10.3/conf/nginx.conf"
    backup_required: true
    syntax_check: "nginx -t"
    reload_command: "systemctl reload nginx"
    
  - path: "/semptian/web/config.js"
    backup_required: true
    syntax_check: "node -c"
    reload_command: "systemctl restart cbp-frontend"

# 回滚配置
rollback_enabled: true
rollback_backup_dir: "{{ backup_base_dir }}"

# 日志配置
log_level: "INFO"
log_file: "/var/log/cbp_ip_change.log"

# 安全配置
dry_run: false  # 设置为true进行预演，不实际修改文件
confirm_before_execute: true
max_concurrent_servers: 3

# 监控配置
monitoring_enabled: true
alert_on_failure: true
notification_webhook: ""  # 可配置钉钉或企业微信webhook

# 验证脚本
post_change_verification:
  - name: "检查Nginx配置"
    command: "nginx -t"
    expected_return_code: 0
    
  - name: "检查Nginx服务状态"
    command: "systemctl is-active nginx"
    expected_output: "active"
    
  - name: "测试CBP登录页面"
    command: "curl -s -o /dev/null -w '%{http_code}' http://192.168.28.9:8104"
    expected_output: "200"
    
  - name: "测试Nacos控制台"
    command: "curl -s -o /dev/null -w '%{http_code}' http://192.168.28.9:8848/nacos"
    expected_output: "200"
