CREATE TABLE v64_deye_dw_ods.ods_nf_url (
    data_type int,
    user_group string,
    user_name string,
    strsrc_ip string,
    strdst_ip string,
    src_port int,
    dst_port int,
    ip_type int,
    file_name string,
    url string,
    domain string,
    dns string,
    title string,
    keyword string,
    net_action string,
    dev_id string,
    terminal_type string,
    app_type string,
    app_name string,
    is_webapp int,
    urllog_type int,
    url_type string,
    url_data string,
    snapshot string,
    trace_t string,
    site string,
    line_id string,
    imei string,
    imsi string,
    mcc string,
    mnc string,
    lac string,
    cell_id string,
    phone_number string,
    capture_time bigint,
    insert_time bigint,
    data_id string,
    uparea_id int,
    insert_day String,
    insert_hour String,
    insert_min String
) WITH (
    'type' = 'hive',
    'catalog' = 'v64_deye_dw_ods',
    'database' = 'v64_deye_dw_ods',
    'config.directory' = '/usr/hdp/current/hive-client/conf/',
    'version' = '3.1.0',
    'jdbc.url' = '172.16.80.10:10000',
    'security.mode.flag' = 'false',
    'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
    'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
    'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
    'partitioned' = 'insert_day String,insert_hour String,insert_min String',
    'streaming-source.enable' = 'false',
    'table.exec.hive.infer-source-parallelism.max' = '32'
);

CREATE TABLE v64_deye_dw_ods.ods_nf_url_store (
    data_type int,
    user_group string,
    user_name string,
    strsrc_ip string,
    strdst_ip string,
    src_port int,
    dst_port int,
    ip_type int,
    file_name string,
    url string,
    domain string,
    dns string,
    title string,
    keyword string,
    net_action string,
    dev_id string,
    terminal_type string,
    app_type string,
    app_name string,
    is_webapp int,
    urllog_type int,
    url_type string,
    url_data string,
    snapshot string,
    trace_t string,
    site string,
    line_id string,
    imei string,
    imsi string,
    mcc string,
    mnc string,
    lac string,
    cell_id string,
    phone_number string,
    capture_time bigint,
    insert_time bigint,
    data_id string,
    uparea_id int,
    capture_day String,
    capture_hour String
) WITH (
    'type' = 'hive',
    'catalog' = 'default',
    'database' = 'v64_deye_dw_ods',
    'config.directory' = '/usr/hdp/current/hive-client/conf/',
    'version' = '3.1.0',
    'createTable' = 'false',
    'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
    'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
    'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
    'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
    'url' = '172.16.80.12:10000',
    'security.mode.flag' = 'false',
    'partitioned' = 'capture_day String,capture_hour String',
    'sink.partition-commit.delay' = '1 min',
    'sink.partition-commit.policy.kind' = 'metastore,success-file',
    'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
);

INSERT INTO
    v64_deye_dw_ods.ods_nf_url_store
SELECT
    data_type,
    user_group,
    user_name,
    strsrc_ip,
    strdst_ip,
    src_port,
    dst_port,
    ip_type,
    file_name,
    url,
    domain,
    dns,
    title,
    keyword,
    net_action,
    dev_id,
    terminal_type,
    app_type,
    app_name,
    is_webapp,
    urllog_type,
    url_type,
    url_data,
    snapshot,
    trace_t,
    site,
    line_id,
    imei,
    imsi,
    mcc,
    mnc,
    lac,
    cell_id,
    phone_number,
    capture_time,
    unix_timestamp()*1000 as insert_time,
    data_id,
    uparea_id,
    from_unixtime(capture_time/1000, 'yyyy-MM-dd') as capture_day,
    from_unixtime(capture_time/1000, 'HH') as capture_hour
FROM
    v64_deye_dw_ods.ods_nf_url
WHERE
    insert_day = from_unixtime(unix_timestamp()-24*3600, 'yyyy-MM-dd');
