CREATE TABLE ods_mobile_radius(
    capture_time Bigint,
    msg_type String,
    action String,
    user_name String,
    nas_ip_address String,
    nas_ipv6_address String,
    nas_identifier String,
    framed_ip_address String,
    internet_ip String,
    port_range String,
    framed_ip_netmask String,
    framed_ipv6_prefix String,
    session_timeout Integer,
    idle_timeout Integer,
    called_station_id String,
    calling_station_id String,
    input_octets Bigint,
    output_octets Bigint,
    session_id String,
    session_time Integer,
    input_packets Integer,
    output_packets Integer,
    terminate_causes String,
    input_gigawords Bigint,
    output_gigawords Bigint,
    imsi String,
    cg_address String,
    sgsn_address String,
    ggsn_address String,
    imsi_mcc_mnc String,
    ggsn_mcc_mnc String,
    session_stop_indicator String,
    cg_ipv6_address String,
    sgsn_ipv6_address String,
    ggsn_ipv6_address String,
    sgsn_mcc_mnc String,
    imeisv String,
    rat_type Integer,
    user_location_info String,
    ms_timezone Integer,
    user_location_info_time String,
    mapping_capture_time Bigint,
    data_id String,
    insert_time Bigint
) WITH (
    'type' = 'kafka',
    'topic' = 'ods_mobile_radius_djezzy',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'group.id' = 'ods_mobile_radius_djezzy_store',
    'format.type' = 'avro',
    'security.mode.flag' = 'false',
    'enable.auto.commit' = 'false',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'feature.max.poll.records' = '1000',
    'feature.fetch.max.bytes' = '11534336',
    'feature.max.partition.fetch.bytes' = '11534336',
    'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
);


CREATE TABLE v64_deye_dw_ods.ods_mobilenet_radius_djezzy_store (
    capture_time Bigint,
    msg_type String,
    action String,
    user_name String,
    nas_ip_address String,
    nas_ipv6_address String,
    nas_identifier String,
    framed_ip_address String,
    internet_ip String,
    port_range String,
    framed_ip_netmask String,
    framed_ipv6_prefix String,
    session_timeout Integer,
    idle_timeout Integer,
    called_station_id String,
    calling_station_id String,
    input_octets Bigint,
    output_octets Bigint,
    session_id String,
    session_time Integer,
    input_packets Integer,
    output_packets Integer,
    terminate_causes String,
    input_gigawords Bigint,
    output_gigawords Bigint,
    imsi String,
    cg_address String,
    sgsn_address String,
    ggsn_address String,
    imsi_mcc_mnc String,
    ggsn_mcc_mnc String,
    session_stop_indicator String,
    cg_ipv6_address String,
    sgsn_ipv6_address String,
    ggsn_ipv6_address String,
    sgsn_mcc_mnc String,
    imeisv String,
    rat_type Integer,
    user_location_info String,
    ms_timezone Integer,
    user_location_info_time String,
    data_id String,
    insert_time Bigint,
    mapping_capture_time Bigint,
    capture_day string,
    capture_hour string
)WITH (
    'type' = 'hive',
    'catalog' = 'default',
    'database' = 'v64_deye_dw_ods',
    'config.directory' = '/usr/hdp/current/hive-client/conf/',
    'version' = '3.1.0',
    'createTable' = 'false',
    'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
    'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
    'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
    'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
    'url' = '172.16.80.12:10000',
    'security.mode.flag' = 'false',
    'partitioned' = 'capture_day String,capture_hour String',
    'sink.partition-commit.delay' = '1 min',
    'sink.partition-commit.trigger' = 'process-time',
    'sink.partition-commit.policy.kind' = 'metastore,success-file',
    'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
);



insert into
    v64_deye_dw_ods.ods_mobilenet_radius_djezzy_store /*+ OPTIONS('sink.partition-commit.delay'='1 min','sink.partition-commit.trigger' = 'process-time','sink.partition-commit.policy.kind'='metastore,success-file','partition.time-extractor.timestamp-pattern'='$capture_day $capture_hour:00:00') */
select
    capture_time,
    msg_type,
    action,
    user_name,
    nas_ip_address,
    nas_ipv6_address,
    nas_identifier,
    framed_ip_address,
    internet_ip,
    port_range,
    framed_ip_netmask,
    framed_ipv6_prefix,
    session_timeout,
    idle_timeout,
    called_station_id,
    calling_station_id,
    input_octets,
    output_octets,
    session_id,
    session_time,
    input_packets,
    output_packets,
    terminate_causes,
    input_gigawords,
    output_gigawords,
    imsi,
    cg_address,
    sgsn_address,
    ggsn_address,
    imsi_mcc_mnc,
    ggsn_mcc_mnc,
    session_stop_indicator,
    cg_ipv6_address,
    sgsn_ipv6_address,
    ggsn_ipv6_address,
    sgsn_mcc_mnc,
    imeisv,
    rat_type,
    user_location_info,
    ms_timezone,
    user_location_info_time,
    data_id,
    unix_timestamp() * 1000 as insert_time,
    mapping_capture_time,
    from_unixtime(capture_time/1000, 'yyyy-MM-dd') as capture_day,
    from_unixtime(capture_time/1000, 'HH')  as capture_hour
from ods_mobile_radius
