
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE ods_pr_shop (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
service_provider String,
username String,
nickname String,
password_hash_string String,
user_id String,
from_shop_id String,
to_shop_id String,
order_id String,
goods_name String,
goods_num Bigint,
money String,
order_time Bigint,
out_time Bigint,
address String,
contact_account_type String,
contact_account String,
leave_word String,
pickup_mobile String,
pickup_certificate_type String,
pickup_certificate_code String,
reg_account_type String,
reg_account String,
pay_account_type String,
pay_account String,
receiver_name String,
third_app String,
sender String,
sender_phone String,
send_address String,
receiver String,
receiver_phone String,
receiver_address String,
delivery_num String,
delivery_company String,
dispatched_phone String,
dispatched_name String,
user_nick String,
total_fee Double,
pay_id String,
goods_id String,
terminal_mac String,
model String,
order_status String,
order_text String,
create_time Bigint,
sms_code String,
shop_keywords String,
sign_name String,
terminal_imei String,
app_pkg_name String,
content String,
ticket_date String,
reg_time Bigint,
shop_addr String,
brand String,
contry_code String,
addr_id String,
head_url String,
goods_attr String,
people_id String,
goods_score String,
deli_time String,
comment_id String,
comment_tags String,
from_id String,
to_id String,
from_name String,
to_name String,
goods_pic String,
friend_head_url String,
from_nickname String,
to_nickname String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
dst_longitude Double,
dst_latitude Double,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_name String,
tool_type String,
isp_id String,
device_id String,
trace_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
pickup_name String,
password String,
url String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_name String,
os_version String,
user_agent String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
remark String,
app_version String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String
)WITH (
      'type' = 'kafka',
    'topic' = 'ods_pr_source_0025_shop',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_pr_shop_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_pr_shop_store (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
service_provider String,
username String,
nickname String,
password_hash_string String,
user_id String,
from_shop_id String,
to_shop_id String,
order_id String,
goods_name String,
goods_num Bigint,
money String,
order_time Bigint,
out_time Bigint,
address String,
contact_account_type String,
contact_account String,
leave_word String,
pickup_mobile String,
pickup_certificate_type String,
pickup_certificate_code String,
reg_account_type String,
reg_account String,
pay_account_type String,
pay_account String,
receiver_name String,
third_app String,
sender String,
sender_phone String,
send_address String,
receiver String,
receiver_phone String,
receiver_address String,
delivery_num String,
delivery_company String,
dispatched_phone String,
dispatched_name String,
user_nick String,
total_fee Double,
pay_id String,
goods_id String,
terminal_mac String,
model String,
order_status String,
order_text String,
create_time Bigint,
sms_code String,
shop_keywords String,
sign_name String,
terminal_imei String,
app_pkg_name String,
content String,
ticket_date String,
reg_time Bigint,
shop_addr String,
brand String,
contry_code String,
addr_id String,
head_url String,
goods_attr String,
people_id String,
goods_score String,
deli_time String,
comment_id String,
comment_tags String,
from_id String,
to_id String,
from_name String,
to_name String,
goods_pic String,
friend_head_url String,
from_nickname String,
to_nickname String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
dst_longitude Double,
dst_latitude Double,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_name String,
tool_type String,
isp_id String,
device_id String,
trace_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
pickup_name String,
password String,
url String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_name String,
os_version String,
user_agent String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
remark String,
app_version String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_pr_shop_store
SELECT
data_type as data_type,
data_source as data_source,
protocol_type as protocol_type,
child_type as child_type,
`action` as `action`,
auth_type as auth_type,
auth_account as auth_account,
proxy_type as proxy_type,
proxy_address as proxy_address,
proxy_provider as proxy_provider,
proxy_account as proxy_account,
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
src_port as src_port,
dst_port as dst_port,
strsrc_ip_v6 as strsrc_ip_v6,
strdst_ip_v6 as strdst_ip_v6,
src_port_v6 as src_port_v6,
dst_port_v6 as dst_port_v6,
src_ip_area as src_ip_area,
dst_ip_area as dst_ip_area,
service_provider as service_provider,
username as username,
nickname as nickname,
password_hash_string as password_hash_string,
user_id as user_id,
from_shop_id as from_shop_id,
to_shop_id as to_shop_id,
order_id as order_id,
goods_name as goods_name,
goods_num as goods_num,
money as money,
order_time as order_time,
out_time as out_time,
address as address,
contact_account_type as contact_account_type,
contact_account as contact_account,
leave_word as leave_word,
pickup_mobile as pickup_mobile,
pickup_certificate_type as pickup_certificate_type,
pickup_certificate_code as pickup_certificate_code,
reg_account_type as reg_account_type,
reg_account as reg_account,
pay_account_type as pay_account_type,
pay_account as pay_account,
receiver_name as receiver_name,
third_app as third_app,
sender as sender,
sender_phone as sender_phone,
send_address as send_address,
receiver as receiver,
receiver_phone as receiver_phone,
receiver_address as receiver_address,
delivery_num as delivery_num,
delivery_company as delivery_company,
dispatched_phone as dispatched_phone,
dispatched_name as dispatched_name,
user_nick as user_nick,
total_fee as total_fee,
pay_id as pay_id,
goods_id as goods_id,
terminal_mac as terminal_mac,
model as model,
order_status as order_status,
order_text as order_text,
create_time as create_time,
sms_code as sms_code,
shop_keywords as shop_keywords,
sign_name as sign_name,
terminal_imei as terminal_imei,
app_pkg_name as app_pkg_name,
content as content,
ticket_date as ticket_date,
reg_time as reg_time,
shop_addr as shop_addr,
brand as brand,
contry_code as contry_code,
addr_id as addr_id,
head_url as head_url,
goods_attr as goods_attr,
people_id as people_id,
goods_score as goods_score,
deli_time as deli_time,
comment_id as comment_id,
comment_tags as comment_tags,
from_id as from_id,
to_id as to_id,
from_name as from_name,
to_name as to_name,
goods_pic as goods_pic,
friend_head_url as friend_head_url,
from_nickname as from_nickname,
to_nickname as to_nickname,
longitude as longitude,
latitude as latitude,
base_station_id as base_station_id,
ownership_land as ownership_land,
internet_land as internet_land,
uparea_id as uparea_id,
dst_longitude as dst_longitude,
dst_latitude as dst_latitude,
lang_type as lang_type,
abstract as abstract,
subject as subject,
text as text,
attach_text as attach_text,
keywords as keywords,
attach_names as attach_names,
attach_sizes as attach_sizes,
attach_md5s as attach_md5s,
attach_num as attach_num,
attach_download_path as attach_download_path,
file_path as file_path,
file_size as file_size,
file_id as file_id,
tool_name as tool_name,
tool_type as tool_type,
isp_id as isp_id,
device_id as device_id,
trace_id as trace_id,
stream_end_time as stream_end_time,
up_teid as up_teid,
down_teid as down_teid,
application_layer_protocol as application_layer_protocol,
tunnel_type as tunnel_type,
imsi as imsi,
imei as imei,
associate_mobile as associate_mobile,
mobile_phone as mobile_phone,
pickup_name as pickup_name,
password as password,
url as url,
local_action as local_action,
mac as mac,
hardware_type as hardware_type,
hardware_sign as hardware_sign,
os_name as os_name,
os_version as os_version,
user_agent as user_agent,
session_id as session_id,
icp_provider as icp_provider,
rule_version as rule_version,
record_id as record_id,
soft_name as soft_name,
favorite_tags as favorite_tags,
host_url_tag as host_url_tag,
remark as remark,
app_version as app_version,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
extend_column as extend_column,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
ods_pr_shop;