
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE ods_pr_im (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
host String,
from_id String,
from_nickname String,
to_id String,
to_nickname String,
user_id String,
user_nick String,
group_num String,
group_name String,
content String,
message_id String,
postal_time Bigint,
delete_status String,
im_encrption_type String,
im_encrption_value String,
flag Integer,
webmail_range_ids String,
webmail_aid String,
media_type String,
other_account_id String,
from_im_id String,
to_im_id String,
sign_name String,
friend_remark String,
org_creater String,
description String,
group_introduce String,
head_url String,
acid3 String,
comment_id String,
topic_id String,
ori_group_id String,
ori_send_id String,
terminal_imei String,
terminal_mac String,
terminal_imsi String,
model String,
group_create_time Bigint,
group_member_count String,
friend_head_url String,
file_url String,
brand String,
group_photo String,
app_pkg_name String,
sms_code String,
city String,
safeuin String,
send_safeuin String,
app_soft_name String,
send_mobile String,
relevant_id String,
dev_id String,
app_id String,
peer_id String,
money String,
trading_account String,
wallet_id String,
from_wallet_id String,
to_wallet_id String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
group_longitude Double,
group_latitude Double,
isp_id String,
device_id String,
trace_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
username String,
password String,
password_hash_string String,
url String,
subject String,
text String,
lang_type String,
abstract String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_text String,
attach_num Integer,
keywords String,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_type String,
tool_name String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_version String,
os_name String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
app_version String,
remark String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
browse_type String
)WITH (
      'type' = 'kafka',
    'topic' = 'ods_pr_source_0005_im',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_pr_im_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_pr_im_store (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
host String,
from_id String,
from_nickname String,
to_id String,
to_nickname String,
user_id String,
user_nick String,
group_num String,
group_name String,
content String,
message_id String,
postal_time Bigint,
delete_status String,
im_encrption_type String,
im_encrption_value String,
flag Integer,
webmail_range_ids String,
webmail_aid String,
media_type String,
other_account_id String,
from_im_id String,
to_im_id String,
sign_name String,
friend_remark String,
org_creater String,
description String,
group_introduce String,
head_url String,
acid3 String,
comment_id String,
topic_id String,
ori_group_id String,
ori_send_id String,
terminal_imei String,
terminal_mac String,
terminal_imsi String,
model String,
group_create_time Bigint,
group_member_count String,
friend_head_url String,
file_url String,
brand String,
group_photo String,
app_pkg_name String,
sms_code String,
city String,
safeuin String,
send_safeuin String,
app_soft_name String,
send_mobile String,
relevant_id String,
dev_id String,
app_id String,
peer_id String,
money String,
trading_account String,
wallet_id String,
from_wallet_id String,
to_wallet_id String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
group_longitude Double,
group_latitude Double,
isp_id String,
device_id String,
trace_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
username String,
password String,
password_hash_string String,
url String,
subject String,
text String,
lang_type String,
abstract String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_text String,
attach_num Integer,
keywords String,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_type String,
tool_name String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_version String,
os_name String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
app_version String,
remark String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
browse_type String,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_pr_im_store
SELECT
data_type as data_type,
data_source as data_source,
protocol_type as protocol_type,
child_type as child_type,
`action` as `action`,
auth_type as auth_type,
auth_account as auth_account,
proxy_type as proxy_type,
proxy_address as proxy_address,
proxy_provider as proxy_provider,
proxy_account as proxy_account,
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
src_port as src_port,
dst_port as dst_port,
strsrc_ip_v6 as strsrc_ip_v6,
strdst_ip_v6 as strdst_ip_v6,
src_port_v6 as src_port_v6,
dst_port_v6 as dst_port_v6,
src_ip_area as src_ip_area,
dst_ip_area as dst_ip_area,
host as host,
from_id as from_id,
from_nickname as from_nickname,
to_id as to_id,
to_nickname as to_nickname,
user_id as user_id,
user_nick as user_nick,
group_num as group_num,
group_name as group_name,
content as content,
message_id as message_id,
postal_time as postal_time,
delete_status as delete_status,
im_encrption_type as im_encrption_type,
im_encrption_value as im_encrption_value,
flag as flag,
webmail_range_ids as webmail_range_ids,
webmail_aid as webmail_aid,
media_type as media_type,
other_account_id as other_account_id,
from_im_id as from_im_id,
to_im_id as to_im_id,
sign_name as sign_name,
friend_remark as friend_remark,
org_creater as org_creater,
description as description,
group_introduce as group_introduce,
head_url as head_url,
acid3 as acid3,
comment_id as comment_id,
topic_id as topic_id,
ori_group_id as ori_group_id,
ori_send_id as ori_send_id,
terminal_imei as terminal_imei,
terminal_mac as terminal_mac,
terminal_imsi as terminal_imsi,
model as model,
group_create_time as group_create_time,
group_member_count as group_member_count,
friend_head_url as friend_head_url,
file_url as file_url,
brand as brand,
group_photo as group_photo,
app_pkg_name as app_pkg_name,
sms_code as sms_code,
city as city,
safeuin as safeuin,
send_safeuin as send_safeuin,
app_soft_name as app_soft_name,
send_mobile as send_mobile,
relevant_id as relevant_id,
dev_id as dev_id,
app_id as app_id,
peer_id as peer_id,
money as money,
trading_account as trading_account,
wallet_id as wallet_id,
from_wallet_id as from_wallet_id,
to_wallet_id as to_wallet_id,
longitude as longitude,
latitude as latitude,
base_station_id as base_station_id,
ownership_land as ownership_land,
internet_land as internet_land,
uparea_id as uparea_id,
group_longitude as group_longitude,
group_latitude as group_latitude,
isp_id as isp_id,
device_id as device_id,
trace_id as trace_id,
stream_end_time as stream_end_time,
up_teid as up_teid,
down_teid as down_teid,
application_layer_protocol as application_layer_protocol,
tunnel_type as tunnel_type,
imsi as imsi,
imei as imei,
associate_mobile as associate_mobile,
mobile_phone as mobile_phone,
username as username,
password as password,
password_hash_string as password_hash_string,
url as url,
subject as subject,
text as text,
lang_type as lang_type,
abstract as abstract,
attach_names as attach_names,
attach_sizes as attach_sizes,
attach_md5s as attach_md5s,
attach_text as attach_text,
attach_num as attach_num,
keywords as keywords,
attach_download_path as attach_download_path,
file_path as file_path,
file_size as file_size,
file_id as file_id,
tool_type as tool_type,
tool_name as tool_name,
local_action as local_action,
mac as mac,
hardware_type as hardware_type,
hardware_sign as hardware_sign,
os_version as os_version,
os_name as os_name,
session_id as session_id,
icp_provider as icp_provider,
rule_version as rule_version,
record_id as record_id,
soft_name as soft_name,
favorite_tags as favorite_tags,
host_url_tag as host_url_tag,
app_version as app_version,
remark as remark,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
extend_column as extend_column,
browse_type as browse_type,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
ods_pr_im;