
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE ods_pr_keyapp (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
host String,
username String,
user_type String,
user_id String,
account_name String,
bank_account String,
deal_money String,
to_id String,
order_id String,
order_time Bigint,
order_cnt String,
goods_id String,
money String,
pay_way String,
from_sex String,
from_id String,
content String,
topic_id String,
publish_time Bigint,
view_times String,
auth_id String,
author String,
friend_head_url String,
other_account_id String,
video_id String,
from_head_url String,
oper_time Bigint,
sms_code String,
coins String,
head_url String,
video_room String,
group_owner_id String,
group_owner_nick String,
group_member_count String,
user_nick String,
read_tags String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
to_nickname String,
from_nickname String,
brand String,
model String,
app_version String,
app_soft_name String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
terminal_imsi String,
terminal_imei String,
password String,
url String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
terminal_mac String,
os_version String,
os_name String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String
)WITH (
      'type' = 'kafka',
    'topic' = 'ods_pr_source_my0017_keyapp',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_pr_keyapp_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_pr_keyapp_store (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
host String,
username String,
user_type String,
user_id String,
account_name String,
bank_account String,
deal_money String,
to_id String,
order_id String,
order_time Bigint,
order_cnt String,
goods_id String,
money String,
pay_way String,
from_sex String,
from_id String,
content String,
topic_id String,
publish_time Bigint,
view_times String,
auth_id String,
author String,
friend_head_url String,
other_account_id String,
video_id String,
from_head_url String,
oper_time Bigint,
sms_code String,
coins String,
head_url String,
video_room String,
group_owner_id String,
group_owner_nick String,
group_member_count String,
user_nick String,
read_tags String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
to_nickname String,
from_nickname String,
brand String,
model String,
app_version String,
app_soft_name String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
terminal_imsi String,
terminal_imei String,
password String,
url String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
terminal_mac String,
os_version String,
os_name String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_pr_keyapp_store
SELECT
data_type as data_type,
data_source as data_source,
protocol_type as protocol_type,
child_type as child_type,
`action` as `action`,
auth_type as auth_type,
auth_account as auth_account,
proxy_type as proxy_type,
proxy_address as proxy_address,
proxy_provider as proxy_provider,
proxy_account as proxy_account,
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
src_port as src_port,
dst_port as dst_port,
strsrc_ip_v6 as strsrc_ip_v6,
strdst_ip_v6 as strdst_ip_v6,
src_port_v6 as src_port_v6,
dst_port_v6 as dst_port_v6,
src_ip_area as src_ip_area,
dst_ip_area as dst_ip_area,
host as host,
username as username,
user_type as user_type,
user_id as user_id,
account_name as account_name,
bank_account as bank_account,
deal_money as deal_money,
to_id as to_id,
order_id as order_id,
order_time as order_time,
order_cnt as order_cnt,
goods_id as goods_id,
money as money,
pay_way as pay_way,
from_sex as from_sex,
from_id as from_id,
content as content,
topic_id as topic_id,
publish_time as publish_time,
view_times as view_times,
auth_id as auth_id,
author as author,
friend_head_url as friend_head_url,
other_account_id as other_account_id,
video_id as video_id,
from_head_url as from_head_url,
oper_time as oper_time,
sms_code as sms_code,
coins as coins,
head_url as head_url,
video_room as video_room,
group_owner_id as group_owner_id,
group_owner_nick as group_owner_nick,
group_member_count as group_member_count,
user_nick as user_nick,
read_tags as read_tags,
longitude as longitude,
latitude as latitude,
base_station_id as base_station_id,
ownership_land as ownership_land,
internet_land as internet_land,
uparea_id as uparea_id,
lang_type as lang_type,
abstract as abstract,
subject as subject,
text as text,
attach_text as attach_text,
keywords as keywords,
attach_names as attach_names,
attach_sizes as attach_sizes,
attach_md5s as attach_md5s,
attach_num as attach_num,
attach_download_path as attach_download_path,
file_path as file_path,
file_size as file_size,
file_id as file_id,
tool_type as tool_type,
tool_name as tool_name,
isp_id as isp_id,
device_id as device_id,
trace_id as trace_id,
session_id as session_id,
icp_provider as icp_provider,
rule_version as rule_version,
record_id as record_id,
soft_name as soft_name,
favorite_tags as favorite_tags,
host_url_tag as host_url_tag,
to_nickname as to_nickname,
from_nickname as from_nickname,
brand as brand,
model as model,
app_version as app_version,
app_soft_name as app_soft_name,
stream_end_time as stream_end_time,
up_teid as up_teid,
down_teid as down_teid,
application_layer_protocol as application_layer_protocol,
tunnel_type as tunnel_type,
imsi as imsi,
imei as imei,
associate_mobile as associate_mobile,
mobile_phone as mobile_phone,
terminal_imsi as terminal_imsi,
terminal_imei as terminal_imei,
password as password,
url as url,
local_action as local_action,
mac as mac,
hardware_type as hardware_type,
hardware_sign as hardware_sign,
terminal_mac as terminal_mac,
os_version as os_version,
os_name as os_name,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
extend_column as extend_column,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
ods_pr_keyapp;