
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE ods_pr_video (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
referer String,
service_provider String,
user_id String,
web_subject String,
video_id String,
video_author String,
copy_from String,
content String,
video_desc String,
video_category String,
video_topic String,
video_pic String,
video_count String,
issue_status String,
comment_id String,
infor_content String,
message String,
from_id String,
to_id String,
terminal_imei String,
address String,
user_nick String,
pickup_name String,
head_url String,
group_name String,
pickup_certificate_code String,
sign_name String,
postal_time Bigint,
reg_time Bigint,
inner_id String,
auth_id String,
like_count String,
trading_account String,
money String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_size Integer,
file_path String,
file_id String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
from_nickname String,
brand String,
model String,
app_version String,
remark String,
message_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
username String,
password String,
url String,
`domain` String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_version String,
os_name String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String
)WITH (
      'type' = 'kafka',
    'topic' = 'ods_pr_source_0038_video',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_pr_video_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_pr_video_store (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
referer String,
service_provider String,
user_id String,
web_subject String,
video_id String,
video_author String,
copy_from String,
content String,
video_desc String,
video_category String,
video_topic String,
video_pic String,
video_count String,
issue_status String,
comment_id String,
infor_content String,
message String,
from_id String,
to_id String,
terminal_imei String,
address String,
user_nick String,
pickup_name String,
head_url String,
group_name String,
pickup_certificate_code String,
sign_name String,
postal_time Bigint,
reg_time Bigint,
inner_id String,
auth_id String,
like_count String,
trading_account String,
money String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_size Integer,
file_path String,
file_id String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
from_nickname String,
brand String,
model String,
app_version String,
remark String,
message_id String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
mobile_phone String,
username String,
password String,
url String,
`domain` String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_version String,
os_name String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_pr_video_store
SELECT
data_type as data_type,
data_source as data_source,
protocol_type as protocol_type,
child_type as child_type,
`action` as `action`,
auth_type as auth_type,
auth_account as auth_account,
proxy_type as proxy_type,
proxy_address as proxy_address,
proxy_provider as proxy_provider,
proxy_account as proxy_account,
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
src_port as src_port,
dst_port as dst_port,
strsrc_ip_v6 as strsrc_ip_v6,
strdst_ip_v6 as strdst_ip_v6,
src_port_v6 as src_port_v6,
dst_port_v6 as dst_port_v6,
src_ip_area as src_ip_area,
dst_ip_area as dst_ip_area,
referer as referer,
service_provider as service_provider,
user_id as user_id,
web_subject as web_subject,
video_id as video_id,
video_author as video_author,
copy_from as copy_from,
content as content,
video_desc as video_desc,
video_category as video_category,
video_topic as video_topic,
video_pic as video_pic,
video_count as video_count,
issue_status as issue_status,
comment_id as comment_id,
infor_content as infor_content,
message as message,
from_id as from_id,
to_id as to_id,
terminal_imei as terminal_imei,
address as address,
user_nick as user_nick,
pickup_name as pickup_name,
head_url as head_url,
group_name as group_name,
pickup_certificate_code as pickup_certificate_code,
sign_name as sign_name,
postal_time as postal_time,
reg_time as reg_time,
inner_id as inner_id,
auth_id as auth_id,
like_count as like_count,
trading_account as trading_account,
money as money,
longitude as longitude,
latitude as latitude,
base_station_id as base_station_id,
ownership_land as ownership_land,
internet_land as internet_land,
uparea_id as uparea_id,
lang_type as lang_type,
abstract as abstract,
subject as subject,
text as text,
attach_text as attach_text,
keywords as keywords,
attach_names as attach_names,
attach_sizes as attach_sizes,
attach_md5s as attach_md5s,
attach_num as attach_num,
attach_download_path as attach_download_path,
file_size as file_size,
file_path as file_path,
file_id as file_id,
tool_type as tool_type,
tool_name as tool_name,
isp_id as isp_id,
device_id as device_id,
trace_id as trace_id,
session_id as session_id,
icp_provider as icp_provider,
rule_version as rule_version,
record_id as record_id,
soft_name as soft_name,
favorite_tags as favorite_tags,
host_url_tag as host_url_tag,
from_nickname as from_nickname,
brand as brand,
model as model,
app_version as app_version,
remark as remark,
message_id as message_id,
stream_end_time as stream_end_time,
up_teid as up_teid,
down_teid as down_teid,
application_layer_protocol as application_layer_protocol,
tunnel_type as tunnel_type,
imsi as imsi,
imei as imei,
associate_mobile as associate_mobile,
mobile_phone as mobile_phone,
username as username,
password as password,
url as url,
`domain` as `domain`,
local_action as local_action,
mac as mac,
hardware_type as hardware_type,
hardware_sign as hardware_sign,
os_version as os_version,
os_name as os_name,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
extend_column as extend_column,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
ods_pr_video;