
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE ods_pr_vpn (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
vpn_src_ip String,
vpn_src_port Integer,
vpn_dst_ip String,
vpn_dst_port Integer,
username String,
user_id String,
tunnel_num String,
tunnel_id String,
server_session_id String,
server_tunel_num String,
pptp_key String,
data_count Bigint,
confidence_level String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
file_md5 String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
is_node_ip String,
app_soft_name String,
app_action String,
app_version String,
model String,
brand String,
op_desc String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
password String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_name String,
os_version String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
browse_type String
)WITH (
      'type' = 'kafka',
    'topic' = 'ods_pr_source_0011_vpn',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_pr_vpn_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_pr_vpn_store (
data_type String,
data_source String,
protocol_type String,
child_type String,
`action` String,
auth_type String,
auth_account String,
proxy_type String,
proxy_address String,
proxy_provider String,
proxy_account String,
strsrc_ip String,
strdst_ip String,
src_port Integer,
dst_port Integer,
strsrc_ip_v6 String,
strdst_ip_v6 String,
src_port_v6 Integer,
dst_port_v6 Integer,
src_ip_area String,
dst_ip_area String,
vpn_src_ip String,
vpn_src_port Integer,
vpn_dst_ip String,
vpn_dst_port Integer,
username String,
user_id String,
tunnel_num String,
tunnel_id String,
server_session_id String,
server_tunel_num String,
pptp_key String,
data_count Bigint,
confidence_level String,
longitude Double,
latitude Double,
base_station_id String,
ownership_land String,
internet_land String,
uparea_id String,
lang_type String,
abstract String,
subject String,
text String,
attach_text String,
keywords String,
attach_names String,
attach_sizes String,
attach_md5s String,
attach_num Integer,
attach_download_path String,
file_path String,
file_size Integer,
file_id String,
file_md5 String,
tool_type String,
tool_name String,
isp_id String,
device_id String,
trace_id String,
session_id String,
icp_provider String,
rule_version String,
record_id String,
soft_name String,
favorite_tags String,
host_url_tag String,
is_node_ip String,
app_soft_name String,
app_action String,
app_version String,
model String,
brand String,
op_desc String,
stream_end_time Bigint,
up_teid String,
down_teid String,
application_layer_protocol String,
tunnel_type String,
imsi String,
imei String,
associate_mobile String,
password String,
local_action String,
mac String,
hardware_type String,
hardware_sign String,
os_name String,
os_version String,
capture_time Bigint,
insert_time Bigint,
data_id String,
extend_column String,
browse_type String,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_pr_vpn_store
SELECT
data_type as data_type,
data_source as data_source,
protocol_type as protocol_type,
child_type as child_type,
`action` as `action`,
auth_type as auth_type,
auth_account as auth_account,
proxy_type as proxy_type,
proxy_address as proxy_address,
proxy_provider as proxy_provider,
proxy_account as proxy_account,
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
src_port as src_port,
dst_port as dst_port,
strsrc_ip_v6 as strsrc_ip_v6,
strdst_ip_v6 as strdst_ip_v6,
src_port_v6 as src_port_v6,
dst_port_v6 as dst_port_v6,
src_ip_area as src_ip_area,
dst_ip_area as dst_ip_area,
vpn_src_ip as vpn_src_ip,
vpn_src_port as vpn_src_port,
vpn_dst_ip as vpn_dst_ip,
vpn_dst_port as vpn_dst_port,
username as username,
user_id as user_id,
tunnel_num as tunnel_num,
tunnel_id as tunnel_id,
server_session_id as server_session_id,
server_tunel_num as server_tunel_num,
pptp_key as pptp_key,
data_count as data_count,
confidence_level as confidence_level,
longitude as longitude,
latitude as latitude,
base_station_id as base_station_id,
ownership_land as ownership_land,
internet_land as internet_land,
uparea_id as uparea_id,
lang_type as lang_type,
abstract as abstract,
subject as subject,
text as text,
attach_text as attach_text,
keywords as keywords,
attach_names as attach_names,
attach_sizes as attach_sizes,
attach_md5s as attach_md5s,
attach_num as attach_num,
attach_download_path as attach_download_path,
file_path as file_path,
file_size as file_size,
file_id as file_id,
file_md5 as file_md5,
tool_type as tool_type,
tool_name as tool_name,
isp_id as isp_id,
device_id as device_id,
trace_id as trace_id,
session_id as session_id,
icp_provider as icp_provider,
rule_version as rule_version,
record_id as record_id,
soft_name as soft_name,
favorite_tags as favorite_tags,
host_url_tag as host_url_tag,
is_node_ip as is_node_ip,
app_soft_name as app_soft_name,
app_action as app_action,
app_version as app_version,
model as model,
brand as brand,
op_desc as op_desc,
stream_end_time as stream_end_time,
up_teid as up_teid,
down_teid as down_teid,
application_layer_protocol as application_layer_protocol,
tunnel_type as tunnel_type,
imsi as imsi,
imei as imei,
associate_mobile as associate_mobile,
password as password,
local_action as local_action,
mac as mac,
hardware_type as hardware_type,
hardware_sign as hardware_sign,
os_name as os_name,
os_version as os_version,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
extend_column as extend_column,
browse_type as browse_type,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
ods_pr_vpn;