CREATE TABLE deye_ods_voip (
    call_id String,
    a_number String,
    a_sip_uri String,
    a_area_code String,
    a_imsi String,
    a_imei String,
    a_neid String,
    a_mcc String,
    a_mnc String,
    a_begin_region String,
    a_begin_cell String,
    a_end_region String,
    a_end_cell String,
    a_point_code String,
    b_number String,
    b_format_number String,
    b_area_code String,
    b_sip_uri String,
    b_orginal_forword_number String,
    b_imsi String,
    b_neid String,
    b_point_code String,
    `action` String,
    start_time Bigint,
    end_time Bigint,
    duration Integer,
    file_path String,
    extend_column String,
    call_type Integer,
    sip_code String,
    isp_id Integer,
    strsrc_ip String,
    strdst_ip String,
    strrtp_ip String,
    third_numbergroup String,
    capture_time Bigint,
    insert_time Bigint,
    data_id String,
    data_type Integer,
    fault_flag Integer
)WITH (
      'type' = 'kafka',
    'topic' = 'deye_ods_voip',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_voip_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_voip_store (
    call_id String,
    a_number String,
    a_sip_uri String,
    a_area_code String,
    a_imsi String,
    a_imei String,
    a_neid String,
    a_mcc String,
    a_mnc String,
    a_begin_region String,
    a_begin_cell String,
    a_end_region String,
    a_end_cell String,
    a_point_code String,
    b_number String,
    b_format_number String,
    b_area_code String,
    b_sip_uri String,
    b_orginal_forword_number String,
    b_imsi String,
    b_neid String,
    b_point_code String,
    `action` String,
    start_time Bigint,
    end_time Bigint,
    duration Integer,
    file_path String,
    extend_column String,
    call_type Integer,
    sip_code String,
    isp_id Integer,
    strsrc_ip String,
    strdst_ip String,
    strrtp_ip String,
    third_numbergroup String,
    capture_time Bigint,
    insert_time Bigint,
    data_id String,
    data_type Integer,
    fault_flag Integer,
    capture_day String,
    capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
    v64_deye_dw_ods.ods_voip_store
SELECT
    call_id,
    a_number,
    a_sip_uri,
    a_area_code,
    a_imsi,
    a_imei,
    a_neid,
    a_mcc,
    a_mnc,
    a_begin_region,
    a_begin_cell,
    a_end_region,
    a_end_cell,
    a_point_code,
    b_number,
    b_format_number,
    b_area_code,
    b_sip_uri,
    b_orginal_forword_number,
    b_imsi,
    b_neid,
    b_point_code,
    action,
    start_time,
    end_time,
    duration,
    file_path,
    extend_column,
    call_type,
    sip_code,
    isp_id,
    strsrc_ip,
    strdst_ip,
    strrtp_ip,
    third_numbergroup,
    capture_time,
    unix_timestamp()*1000 as insert_time,
    data_id,
    data_type,
    fault_flag,
    from_unixtime(capture_time/1000, 'yyyy-MM-dd') as capture_day,
    from_unixtime(capture_time/1000, 'HH') as capture_hour
FROM
    deye_ods_voip;