
CREATE SCALAR FUNCTION deyeTimestampConverter WITH com.semptian.udf.timestamphandle.DeyeTimestampConverter;

CREATE TABLE deye_ods_voip_fax (
strsrc_ip String,
strdst_ip String,
sender_from_url String,
receiver_to_url String,
sender_sip_number String,
receiver_sip_number String,
call_id String,
sender_nickname String,
receiver_nickname String,
start_time Bigint,
end_time Bigint,
duration Integer,
media_type String,
media_protocol String,
media_format String,
file_path String,
file_size Integer,
capture_time Bigint,
insert_time Bigint,
data_id String,
data_type Integer,
fault_flag Integer
)WITH (
      'type' = 'kafka',
    'topic' = 'deye_ods_voip_fax',
    'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
    'security.mode.flag' = 'false',
    'group.id' = 'ods_voip_fax_store',
    'enable.auto.commit' = 'true',
    'auto.commit.interval.ms' = '6000',
    'auto.offset.reset' = 'latest',
    'session.timeout.ms' = '30000',
    'format.type' = 'avro',
    'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
    );

CREATE TABLE v64_deye_dw_ods.ods_voip_fax_store (
strsrc_ip String,
strdst_ip String,
sender_from_url String,
receiver_to_url String,
sender_sip_number String,
receiver_sip_number String,
call_id String,
sender_nickname String,
receiver_nickname String,
start_time Bigint,
end_time Bigint,
duration Integer,
media_type String,
media_protocol String,
media_format String,
file_path String,
file_size Integer,
capture_time Bigint,
insert_time Bigint,
data_id String,
data_type Integer,
fault_flag Integer,
capture_day String,
capture_hour String
)WITH (
     'type' = 'hive',
	'catalog' = 'default',
	'database' = 'v64_deye_dw_ods',
	'config.directory' = '/usr/hdp/current/hive-client/conf/',
	'version' = '3.1.0',
	'createTable' = 'false',
	'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
	'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
	'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
	'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
	'url' = '172.16.80.12:10000',
	'security.mode.flag' = 'false',
	'partitioned' = 'capture_day String,capture_hour String',
	'sink.partition-commit.delay' = '1 min',
	'sink.partition-commit.policy.kind' = 'metastore,success-file',
	'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
    );

INSERT INTO 
 v64_deye_dw_ods.ods_voip_fax_store
SELECT
strsrc_ip as strsrc_ip,
strdst_ip as strdst_ip,
sender_from_url as sender_from_url,
receiver_to_url as receiver_to_url,
sender_sip_number as sender_sip_number,
receiver_sip_number as receiver_sip_number,
call_id as call_id,
sender_nickname as sender_nickname,
receiver_nickname as receiver_nickname,
start_time as start_time,
end_time as end_time,
duration as duration,
media_type as media_type,
media_protocol as media_protocol,
media_format as media_format,
file_path as file_path,
file_size as file_size,
capture_time as capture_time,
deyeTimestampConverter(data_id) as insert_time,
data_id as data_id,
data_type as data_type,
fault_flag,
deyeTimestampConverter(capture_time,'yyyy-MM-dd') as capture_day,
deyeTimestampConverter(capture_time,'HH') as capture_hour
FROM
deye_ods_voip_fax;