
CREATE TABLE deye_ods_nf_target (
    data_type Integer,
    user_group String,
    user_name String,
    strsrc_ip String,
    strdst_ip String,
    src_port Integer,
    dst_port Integer,
    protocol Integer,
    url String,
    dns String,
    net_action Integer,
    chat_action String,
    chat_dir String,
    dev_id String,
    mac String,
    terminal_type String,
    app_type String,
    app_name String,
    decrypt String,
    mail_from String,
    mail_to String,
    mail_title String,
    capture_time bigint,
    uparea_id Integer,
    insert_time bigint,
    data_id String
) WITH (
	'type' = 'kafka',
	'topic' = 'deye_ods_nf_target',
	'bootstrap.servers' = 'hdp-01:6667,hdp-02:6667,hdp-03:6667,hdp-04:6667,hdp-07:6667,hdp-05:6667,hdp-06:6667,hdp-08:6667',
    'zookeeper.connect' = 'hdp-01:2181,hdp-02:2181,hdp-03:2181,hdp-04:2181,hdp-07:2181,hdp-05:2181,hdp-06:2181',
	'group.id' = 'case_store',
	'format.type' = 'avro',
	'security.mode.flag' = 'false',
	'enable.auto.commit' = 'false',
	'auto.commit.interval.ms' = '6000',
	'auto.offset.reset' = 'latest',
	'session.timeout.ms' = '30000',
	'feature.max.poll.records' = '1000',
	'feature.fetch.max.bytes' = '11534336',
	'feature.max.partition.fetch.bytes' = '11534336',
	'feature.fetch.message.max.bytes' = '11534336',
    'feature.request.timeout.ms' = '120000'
);


CREATE TABLE v64_deye_dw_ods.ods_nf_target_store(
    data_type int,
    user_group String,
    user_name String,
    strsrc_ip String,
    strdst_ip String,
    src_port int,
    dst_port int,
    protocol int,
    url String,
    dns String,
    net_action int,
    chat_action String,
    chat_dir String,
    dev_id String,
    mac String,
    terminal_type String,
    app_type String,
    app_name String,
    decrypt String,
    mail_from String,
    mail_to String,
    mail_title String,
    capture_time bigint,
    uparea_id int,
    insert_time bigint,
    data_id String,
    capture_day String,
    capture_hour String
)
WITH (
    'type' = 'hive',
    'catalog' = 'v64_deye_dw_ods',
    'database' = 'v64_deye_dw_ods',
    'config.directory' = '/usr/hdp/current/hive-client/conf/',
    'version' = '3.1.0',
    'createTable' = 'false',
    'jdbc.url' = 'jdbc:hive2://172.16.80.12:10000',
    'yarn-site.xml' = '/usr/hdp/current/hadoop-client/conf/yarn-site.xml',
    'core-site.xml' = '/usr/hdp/current/hadoop-client/conf/core-site.xml',
    'hdfs-site.xml' = '/usr/hdp/current/hadoop-client/conf/hdfs-site.xml',
    'url' = '172.16.80.12:10000',
    'security.mode.flag' = 'false',
    'partitioned' = 'capture_day String,capture_hour String',
    'sink.partition-commit.delay' = '1 min',
    'sink.partition-commit.trigger' = 'process-time',
    'sink.partition-commit.policy.kind' = 'metastore,success-file',
    'partition.time-extractor.timestamp-pattern' = '$capture_day $capture_hour:00:00'
);


insert into v64_deye_dw_ods.ods_nf_target_store
/*+ OPTIONS('sink.partition-commit.delay'='1 min','sink.partition-commit.trigger' = 'process-time','sink.partition-commit.policy.kind'='metastore,success-file','partition.time-extractor.timestamp-pattern'='$capture_day $capture_hour:00:00') */
select
    data_type,
    user_group,
    user_name,
    strsrc_ip,
    strdst_ip,
    src_port,
    dst_port,
    protocol,
    url,
    dns,
    net_action,
    chat_action,
    chat_dir,
    dev_id,
    mac,
    terminal_type,
    app_type,
    app_name,
    decrypt,
    mail_from,
    mail_to,
    mail_title,
    capture_time,
    uparea_id,
    unix_timestamp() * 1000 as insert_time,
    data_id,
    from_unixtime(cast(capture_time as bigint)/1000,'yyyy-MM-dd') as capture_day,
    from_unixtime(cast(capture_time as bigint)/1000,'HH') as capture_hour
from deye_ods_nf_target
