---
# Ansible Playbook for adding Doris cluster hosts configuration to Hadoop cluster
# 用于在Hadoop集群节点上增量添加Doris集群hosts配置的脚本
#
# 使用方法:
# ansible-playbook -i inventory/hadoop.ini hadoop-doris-hosts-update.yml
# 或者指定Doris网络段:
# ansible-playbook -i inventory/hadoop.ini hadoop-doris-hosts-update.yml --extra-vars "doris_network=192.168.28"

- name: "增量添加Doris集群hosts配置到Hadoop集群"
  hosts: hadoop_cluster
  gather_facts: no  # 不收集系统信息，加快执行速度
  # 添加错误处理策略 - 跳过不可达节点继续执行
  strategy: free
  any_errors_fatal: false
  ignore_unreachable: true
  # 添加超时和并发控制
  serial: 20  # 每批处理20个节点
  timeout: 30  # 任务超时30秒
  vars:
    doris_network: "{{ doris_network | default('192.168.15') }}"
    backup_suffix: "{{ 99999999 | random }}"  # 简化时间戳为随机数

  # 移除pre_tasks，直接执行主要任务

  tasks:
    # 简化版本：直接添加Doris配置，自动处理重复项
    - name: 移除旧的Doris配置（如果存在）
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} DORIS CLUSTER HOSTS"
        state: absent
      ignore_errors: yes

    - name: 添加Doris集群hosts配置
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} DORIS CLUSTER HOSTS"
        block: |
          # Doris集群 - 数据仓库 ({{ doris_network }}.x)
          # FE节点 (Frontend)
          {{ doris_network }}.101 doris-s1 doris-fe-1
          {{ doris_network }}.103 doris-s3 doris-fe-2
          {{ doris_network }}.111 doris-s11 doris-fe-3
          {{ doris_network }}.112 doris-s12 doris-fe-master doris-master
          {{ doris_network }}.120 doris-s20 doris-fe-4

          # BE节点 (Backend) 和管理节点
          {{ doris_network }}.102 doris-s2 doris-manager
          {{ doris_network }}.104 doris-s4
          {{ doris_network }}.105 doris-s5
          {{ doris_network }}.106 doris-s6
          {{ doris_network }}.107 doris-s7
          {{ doris_network }}.108 doris-s8
          {{ doris_network }}.109 doris-s9
          {{ doris_network }}.110 doris-s10
          {{ doris_network }}.113 doris-s13
          {{ doris_network }}.114 doris-s14
          {{ doris_network }}.115 doris-s15
          {{ doris_network }}.116 doris-s16
          {{ doris_network }}.117 doris-s17
          {{ doris_network }}.118 doris-s18
          {{ doris_network }}.119 doris-s19
          {{ doris_network }}.121 doris-s21
          {{ doris_network }}.122 doris-s22
          {{ doris_network }}.123 doris-s23
          {{ doris_network }}.124 doris-s24
          {{ doris_network }}.125 doris-s25
          {{ doris_network }}.126 doris-s26
          {{ doris_network }}.127 doris-s27
          {{ doris_network }}.128 doris-s28
          {{ doris_network }}.129 doris-s29
          {{ doris_network }}.130 doris-s30
          {{ doris_network }}.131 doris-s31
          {{ doris_network }}.132 doris-s32
          {{ doris_network }}.133 doris-s33
        backup: yes
      ignore_errors: yes

# 简化完成 - 只添加hosts配置，不做额外验证
